### ISSUE TITLE
InsertFromQuery Doesn't seem to work

### ISSUE THREAD

**Issue by npbenjohnson** [zzzprojects/EntityFramework-Extensions#330] opened 2020-04-15 01:59 UTC
### Description
No matter how I try to use InsertFromQuery I either get a "index out of range" or "object not set to an instance" error. I posted 6 very simple attempts forked off of the demo fiddle for UpdateFromQuery.

### Attempts (also posted in the fiddle)

```
//context.Customers.Where(x => x.Counter >= 1).InsertFromQuery(x => new Customer {Counter = x.Counter + 10});
//context.Customers.Where(x => x.Counter >= 1).InsertFromQuery(x => new {x.Counter});
//context.Customers.Where(x => x.Counter >= 1).InsertFromQuery(x => new {CustomerID = x.CustomerID * 10, x.Counter});
//context.Customers.Where(x => x.Counter >= 1).InsertFromQuery(x => new Customer {CustomerID = x.CustomerID * 10, Counter =x.Counter});
//context.Customers.Where(x => x.Counter >= 1).InsertFromQuery(x => new Customer {CustomerID = x.CustomerID * 10, Name="asdf", Counter =x.Counter});
context.Customers.Where(x => x.Counter >= 1).InsertFromQuery("Customers", x => new Customer {CustomerID = x.CustomerID * 10, Name="asdf", Counter =x.Counter});
```

### Exception
```
Unhandled exception. System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at `1..( )
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.String.Join(String separator, IEnumerable`1 values)
   at `1.()
   at `1.Execute(IQueryable`1 query, String databaseName, String schemaName, String tableName, Expression`1 selectFieldsExpression, Type tableType)
   at DbContextExtensions.[](IQueryable`1 , String , String , String , Expression`1 , Type )
   at DbContextExtensions.InsertFromQuery[TEntity](IQueryable`1 query, String tableName, Expression`1 selectFieldsExpression)
   at Program.Main()
Command terminated by signal 6
```

### Fiddle or Project (Optional)

https://dotnetfiddle.net/oWws8x

### Further technical details
- EF version:
- EF Extensions version:
- Database Provider:

**Comment by JonathanMagnan** [comment] 2020-04-15 16:08
Hello @npbenjohnson ,

Thank you for reporting, we are currently looking at it.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment] 2020-04-17 14:32
Hello @npbenjohnson ,

The issue is now fixed.

However, you still have an error since you try to insert in an identity column.

I asked to my developer to add an option to turn off the identity insert to allow this kind of behavior.

**Comment by JonathanMagnan** [comment] 2020-04-17 14:39
First, do you really need this feature (insert into an identity column)?

It will require us to first query the table to check if there is an identity column which is pretty weird I believe for the `InsertFromQuery` method.

**Comment by npbenjohnson** [comment] 2020-04-17 23:20
No, I don't need the identity column as a feature, I was just trying anything to get it to work in general, thanks for finding a fix.

**Closed** 2020-04-18 18:08 UTC
