### ISSUE TITLE
Bulk operation fails with default value.

### ISSUE THREAD

**Issue by ordinarytype** [zzzprojects/EntityFramework-Extensions#316] opened 2020-01-10 13:05 UTC
Hello @JonathanMagnan,

I've found an issue (pretty similar to this [one](https://github.com/zzzprojects/EntityFramework-Extensions/issues/198)) that bulk operation fails conversion to DateTimeOffSet.  
We're using 10.3.11-MariaDB.
Sample project is attached.

Thanks!
[BulkIssue.zip](https://github.com/zzzprojects/EntityFramework-Extensions/files/4045695/BulkIssue.zip)

**Comment by JonathanMagnan** [comment] 2020-01-13 21:45
Hello @ordinarytype ,

The v3.0.37 has been released.

Could you try it and confirm us that the issue is fixed?

Best Regards,

Jon

**Comment by ordinarytype** [comment] 2020-01-14 06:48
Hello @JonathanMagnan 

Yes, issue is fixed. Could you please duplicate this fix to the latest EF Extensions v2.x version?

**Comment by JonathanMagnan** [comment] 2020-01-14 14:19
If you mean for EF Core 2.x, that's already released: https://www.nuget.org/packages/Z.EntityFramework.Extensions.EFCore/2.7.37

I don't think it has been released yet for `EF6` but it will be part of the next release (which we normally release almost every week)

**Comment by ordinarytype** [comment] 2020-01-14 14:37
Yep, issue is fixed in 2.7.37, thank you.

**Closed** 2020-01-21 13:51 UTC
