### ISSUE TITLE
Exception on BulkSaveChanges when Table has Computed Column

### ISSUE THREAD

**Issue by scsabalevente** [zzzprojects/EntityFramework-Extensions#222] opened 2019-06-04 12:19 UTC
Hello,

I have the same issue as https://github.com/zzzprojects/EntityFramework-Extensions/issues/125 which is already closed but not working for me. Could you help me?
I use version 3.18.5 and ForceSelectOutput does not solves it:
`ctx.BulkSaveChanges(Function(options) options.ForceSelectOutput = True)`

Here is the error I get:
`{"The column reference ""inserted.DESCRIPTION"" is not allowed because it refers to a base table that is not being modified in this statement." & vbCrLf & "Column 'inserted.AR' cannot be referenced in the OUTPUT clause because the column definition contains a subquery or references a function that performs user or system data access. A function is assumed by default to perform data access if it is not schemabound. Consider removing the subquery or function from the column definition or removing the column from the OUTPUT clause." & vbCrLf & "The column reference ""inserted.ST_SHORT_DESC"" is not allowed because it refers to a base table that is not being modified in this statement."}`

Can you help me, please?

Best Regards,
Csaba

**Comment by JonathanMagnan** [comment] 2019-06-04 13:46
Hello @scsabalevente ,

Could you try to set it globally `EntityFrameworkManager.ForceSelectOutput = true` to see if that work.

The current statement doesn't seem the right one when this option is enabled.

I added a task to check if the `ForceSelectOutput` work correctly when specified in the BulkSaveChanges. I believe we have an issue here.

Best Regards,

Jonathan

**Comment by scsabalevente** [comment] 2019-06-04 14:04
I tried it but having the same result/error with below code:
EntityFrameworkManager.ForceSelectOutput = True
ctx.BulkSaveChanges()   

(Before we used ctx.SaveChanges() and that was working but we would like to improve the performance of our product)

**Comment by JonathanMagnan** [comment] 2019-06-04 14:27
We should be able to look at it in a few hours.

Meanwhile, if you use EF6, I suggest you to tries `BatchSaveChanges` instead. This method should already work without having to do any options.

In short, `BatchSaveChanges` re-use the same SQL Command as Entity Framework but batches them in fewer command so improve the performance by reducing the number of database round-trip required.

**Comment by scsabalevente** [comment] 2019-06-05 08:23
Indeed, the `BatchSaveChanges` works fine.
Please let me know if there are any news related to `BulkSaveChanges`.

**Comment by scsabalevente** [comment] 2019-06-06 07:58
We tested the performance in a scenario in which all 3 methods are working with below result:
```
1. SaveChanges: ~3 min
2. BatchSaveChanges: ~5 min
3. BulkSaveChanges: ~10 sec
```

We cannot use BatchSaveChanges because it went slower than the normal save. 
Do you have some news if you can fix BulkSaveChanges?

KR,
Csaba

**Comment by JonathanMagnan** [comment] 2019-06-06 13:03
Hello @scsabalevente ,

Unfortunately, we tried several times (with different developers) but we did succeed reproduced it on our side.

When the options `ForceSelectOutput` is enabled. Our library generates a different SQL Command as yours.

It is possible for you to provide a runnable solution with this issue? You can send it in private here: info@zzzprojects.com

Having a project that reproduces it will allow us to focus on the solution instead of trying to reproduce the problem.

**Comment by scsabalevente** [comment] 2019-06-06 14:17
Thanks for the answer @JonathanMagnan.
We will try to reproduce the problem on a smaller solution but I doubt that we will succeed.

Is it normal that `BatchSaveChanges` is slower than `SaveChanges`? (see my previous comment)

**Comment by JonathanMagnan** [comment] 2019-06-06 14:58
It could be on a very bad SQL Server. `BatchSaveChanges` require more time to create the query plan for example.

We already opened an issue on our side to check it.

Is it possible to provide us, for example, SQL Profiler log which compares SaveChanges vs BatchSaveChanges?

**Comment by scsabalevente** [comment] 2019-06-11 09:24
We cannot send the SQL Profiler logs because it contains sensitive data.

**Comment by scsabalevente** [comment] 2019-06-13 11:52
Hello,

I managed to reproduce the issue with `BulkSaveChanges `in a small project:
[Test_BulkSaveChanges.zip](https://github.com/zzzprojects/EntityFramework-Extensions/files/3285815/Test_BulkSaveChanges.zip)

Follow the instructions from the readme file.

KR,
Csaba

**Comment by scsabalevente** [comment] 2019-06-13 12:05
I forgot, do not open the edmx in designer. Instead use xml text editor, if you want to open it.

**Comment by JonathanMagnan** [comment] 2019-06-13 17:50
Great thank you,

We will look at it very soon

**Comment by JonathanMagnan** [comment] 2019-06-18 00:41
Hello @scsabalevente ,

The performance issue with `BatchSaveChanges` has been fixed in the latest version. You were right, a configuration was not taken which dramatically impacted the performance of this method when used with thousands of entities.

We also made a lot of change toward an issue very similar to yours. I will look at your project later this night to verify if your issue has been fixed with our recent changes or your is different.

**Comment by JonathanMagnan** [comment] 2019-06-18 03:08
Hello @scsabalevente ,

After verification, your issue is not exactly the same. In your case, in addition, you are currently using a view and not directly the table.

We released a new version (v3.20.4). Your project is now working with this new version.

Let me know if everything is working as expected.

Best Regards,

Jonathan

**Comment by scsabalevente** [comment] 2019-06-18 11:22
Hello @JonathanMagnan ,

Thank you for the update!
The initial error message within `BulkSaveChanges` is solved.
Also tested `BatchSaveChanges` and there is a significant improvement:
`SaveChanges: 6 min
BatchSaveChanges: 1 min
BulkSaveChanges: 15 sec`

Unfortunately  there is a scenario where both methods crash with following error message:
`"Saving or accepting changes failed because more than one entity of type 'my_entity' have the same primary key value. Ensure that explicitly set primary key values are unique. Ensure that database-generated primary keys are configured correctly in the database and in the Entity Framework model. Use the Entity Designer for Database First/Model First configuration. Use the 'HasDatabaseGeneratedOption"" fluent API or 'DatabaseGeneratedAttribute' for Code First configuration."`

With the `SaveChanges` method we avoid this crash by calling it with following parameter: `SaveChanges(SaveOptions.None)`

Is there a setting like `SaveOptions.None` for `BulkSaveChanges` or `BatchSaveChanges`? I didn't see.

Thanks,
Csaba

**Comment by JonathanMagnan** [comment] 2019-06-18 12:06
Awesome,

`BatchSaveChanges` is expected to increase performance by 5-10x, so we fit in this range ;)

I believe you are looking for this option:

```
ctx.BulkSaveChanges(x => x.SkipPropagationAndAcceptChanges = true);
```

Let me know if you still receive the same error, we will look deeper on it.

**Comment by scsabalevente** [comment] 2019-06-18 12:32
I receive the same error. Any other ideas?

**Comment by scsabalevente** [comment] 2019-06-20 12:04
Do you have any update on this?
We also encounter another issue:
`The transaction associated with the current connection has completed but has not been disposed.  The transaction must be disposed before the connection can be used to execute SQL statements.`

There are 2 open topics now.
Should we log these issues separately in separate tickets?

**Comment by JonathanMagnan** [comment] 2019-06-20 12:36
Oh sorry, I missed your first message. We will look at it in a few minutes

About the second issue, that usually happens cause of an async method with a transaction scope.

For example, do you have similar code as this one in your project:

```csharp
Task task = null;
using (var transaction = new TransactionScope())
{
	task = ctx.BulkInsertAsync(list);
}

Task.WaitAll(task);
```

Since the task is created inside a transaction scope but might be executed outside, it will sometime throw this kind of error.

**Comment by JonathanMagnan** [comment] 2019-06-20 16:08
Hello @scsabalevente ,

Just to let you know, we are not able to reproduce the issue for the `BulkSaveChanges` but we can easily reproduce it in `BatchSaveChanges`. A new version should soon be released for at this method.

**Comment by JonathanMagnan** [comment] 2019-06-20 18:53
Hello @scsabalevente ,

The v3.20.6 has been released.

For `BatchSaveChanges`, we added an overload to let you pass the `SaveOptions`

```csharp
ctx.GetObjectContext().BatchSaveChanges(SaveOptions.None);
```

However, we tried several things on our side and the `SkipPropagationAndAcceptChanges` doesn't accept the changes as expected.

Is it possible to update your project and provide an example that doesn't work?

**Comment by scsabalevente** [comment] 2019-06-21 09:10
Thanks for the fast feedback!

`BatchSaveChanges(SaveOptions.None)` is working.
We will see if we can reproduce the issue with `BulkSaveChanges`.

(You mentioned: `BatchSaveChanges` is expected to increase performance by 5-10x.)
Can you give us the estimate of performance increase for `BulkSaveChanges`?

Are there scenarios where `BatchSaveChanges` is faster than `BulkSaveChanges` or you always recommend to use `BulkSaveChanges`? Or when should we use `BatchSaveChanges` over `BulkSaveChanges`? From the documentation I assume `BulkSaveChanges` is always faster and better than `BatchSaveChanges` but I am not sure :) maybe I misunderstand something...

**Comment by JonathanMagnan** [comment] 2019-06-21 10:13
We probably need to update our documentation ;) `BatchSaveChanges` has been added recently so some of our documentation is probably outdated.

Most people report us performance improvement of around 20-25x with `BulkSaveChanges`. 

If your model supports it, you can easily get better performance (30-40x) by using `BulkSaveChanges(false)`. It uses less method coming from `Entity Framework` (so faster) but doesn't support everything yet (https://entityframework-extensions.net/improve-bulk-savechanges).

Obviously, performance can only be here when you have A LOT of entities to saves. We cannot be faster when there is only one entity to save.

Here is my opinion,

`BatchSaveChanges` should replace all `SaveChanges`. It is as fast as `SaveChanges` for one entity but become faster when there is more than one entity to saves. The `BatchSaveChanges` will outperform `BulkSaveChanges` for a while but after a few hundreds of entities in the ChangeTracker, the `BulkSaveChanges` will start to become a more scalable solution.

The `BatchSaveChanges` use the same exact SQL as `SaveChanges` does but batches them in fewer command so fewer database round-trips are required which improve the performance.

The `BulkSaveChanges` use his own SQL. Using `SqlBulkCopy` and temporary/variable table under the hood.

**Comment by scsabalevente** [comment] 2019-06-21 11:42
Thanks for the explanation!

**Comment by scsabalevente** [comment] 2019-06-26 09:01
Is there a chance that the performance was affected when you introduced `SaveOptions` for `BatchSaveChanges`?
Instead of 1 min we get 3.5 min in our test.
Can you test this?

**Comment by JonathanMagnan** [comment] 2019-06-26 11:02
Weird,

I double verified, besides adding 2 `if` statements to handle different `SaveOptions` value, nothing has been really done in this method.

Is it possible that you used `debug` mode and the first time you use `release` mode or something like this?

On our side, I made the mistake to forget to remove a `DbCommandInterceptor` that was logging in the `Console`. So I got a very huge performance hit on the first time I tried our benchmark this morning.

**Comment by scsabalevente** [comment] 2019-06-26 11:37
I repeated the same test several times in `release mode` and monitoring with `SQL Server Profiler` and I had different results between 2 min and 6 min...

**Comment by JonathanMagnan** [comment] 2019-06-26 11:44
That weird,

Which version are you using?

**Comment by scsabalevente** [comment] 2019-06-26 12:20
I use version 3.20.6

**Comment by scsabalevente** [comment] 2019-06-27 11:32
I restarted my machine and retested both `BatchSaveChanges` and `BatchSaveChanges(SaveOptions.None)`. I repeated the same test 3 times in both cases (6 tests) and now I have the same result for both tests which is 1 min (as expected).

Still don't know what happened before the restart...
Anyway, sorry for the inconvenience!

**Comment by scsabalevente** [comment] 2019-06-27 11:55
Question: You mentioned that "`The BatchSaveChanges will outperform BulkSaveChanges for a while...`" but will `SaveChanges` outperform `BulkSaveChanges` when we save only 1 entity for example?

**Comment by JonathanMagnan** [comment] 2019-06-27 11:56
No problem, thank A LOT for letting us know ;)

Made test on my side and got result as expected.

My employee who made the change was about to check it but I guess I can tell him to only make a few basic tests instead.

**Comment by JonathanMagnan** [comment] 2019-06-27 12:02
> but will SaveChanges outperform BulkSaveChanges when we save only 1 entity for example

I believe you mean `BatchSavechanges` in this sentence.

In `EF Classic`, both have a similar result (only a few `if` is called)
In `EF Extensions`, there are little initial times the first time you use the method to compile some lambda expression that uses EF internal methods. But both have a very similar result. 

Under the hood, our library will call the same method as `SaveChanges` does when there is nothing to batches.

**Comment by scsabalevente** [comment] 2019-06-27 12:24
We have one general save function for all kind of objects.
How do we decide to call `BatchSavechanges` or `BulkSaveChanges` ?
For example (this is a stupid example):
`           Dim lCount As Integer = 0
            For Each entity In ChangeTracker.Entries
                If entity.State <> EntityState.Unchanged Then
                    lCount = lCount + 1
                End If
            Next
            If lCount > 100 Then
                MyBase.BulkSaveChanges()
            Else
                MyBase.BatchSaveChanges()
            End If`

**Comment by JonathanMagnan** [comment] 2019-06-27 16:22
Depending on your situation, I would probably always use `SaveChanges` by default and for some well know critical performance part of the application use `BulkSaveChanges` and other `Bulk Operations` at those place.

But if I had to do something similar, here is what I would probably do it in C#:

```csharp
public override int SaveChanges()
{
	this.ChangeTracker.DetectChanges();
	var entriesCount = this.GetObjectContext().ObjectStateManager.GetObjectStateEntries(EntityState.Added | EntityState.Modified | EntityState.Deleted).Count();
	
	if(entriesCount > 200)
	{
		this.BulkSaveChanges();
		return -1;
	}
	else
	{
		return this.BatchSaveChanges();
	}
}
```

**Comment by scsabalevente** [comment] 2019-07-02 15:16
Let's say I have in the `ChangeTracker` 200 entities of different types (save is happening in 200 tables).
Does above code applies in this situation?

We have a scenario where we get below results:
```
1. SaveChanges: 14 min
2. BatchSaveChanges: 10 min
3. BulkSaveChanges: 24 min
```
The save function is called 2000 times in total...above result = the total time of 2000 calls.

**Comment by JonathanMagnan** [comment] 2019-07-03 02:34
So you are saving 1 entity per table if I understand?

Obviously, `BulkSaveChanges` will perform very bad in this case. So no, I would not use the code I provided.

If you have too much table, you must not blindly call `BulkSaveChanges`. As you have seen, the performance can be worse in some limit scenario like this one.

But this situation will unlikely happen (unless that make sense in your case). When you have 200 entries, they are normally split in 5-10 tables, not in 200 tables.

**Comment by scsabalevente** [comment] 2019-07-03 14:19
Hello @JonathanMagnan ,

Thanks a lot for all the fixes and answers!
It seems that we can use `BatchSaveChanges` for now and also we will try to use `BulkSaveChanges` in some specific scenarios.

I don't close this thread yet in order to have a communication channel open if we encounter further issues.

Thanks,
Csaba

**Comment by JonathanMagnan** [comment] 2019-07-30 04:35
Hello @scsabalevente ,

We will close this issue on our side since we got no discussion in almost one month.

If there is anything, just add a comment here and we will re-open it (You can also simply create a new one).

Best Regards,

Jonathan

**Closed by JonathanMagnan** 2019-07-30 04:35 UTC
