### ISSUE TITLE
Batch Insert with SQLite

### ISSUE THREAD

**Issue by SerenaFA** [zzzprojects/EntityFramework-Extensions#604] opened 2024-09-20 09:09 UTC
Got the following error when using BatchInsert with a sqlite context.

  This exception was originally thrown at this call stack:
    .(string)
    .(bool, Z.BulkOperations.BulkOperation)
    .()
    Z.BulkOperations.BulkOperation.()

Inner Exception 1:
Exception: The following type 'varchar]' is not yet supported for the provider 'SQLiteMicrosoft'. Please report the issue to our support team: info@zzzprojects.com , v=8.103.3.0

**Comment by JonathanMagnan** [comment] 2024-09-20 13:51
Hello @SerenaFA ,

Indeed the type `varchar]` is not supported. You can see there is a closing square bracket in the type name `]`

Strangely, SQLite allows you to put anything for the type.

If you fix it to use the type `varchar` instead of  `varchar]`, everything should now work correctly.

Let me know if that explain correctly the cause and solution to this problem.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment] 2024-09-23 13:43
Hello @SerenaFA, 

Since our last conversation, we haven't heard from you. 

Let me know if you need further assistance. 

Best regards, 

Jon

**Comment by SerenaFA** [comment] 2024-09-23 13:54
We updated our table to use TEXT column type and this solved the issue for this case thanks.

**Closed** 2024-09-23 13:53 UTC
