### ISSUE TITLE
The destination table name could not be found. It's normally happen for unsupported provider.

### ISSUE THREAD

**Issue by jrt324** [zzzprojects/EntityFramework-Extensions#36] opened 2017-04-28 08:38 UTC
when i call  dbContext.BulkInsert(members) , it's throw this exception

`The destination table name could not be found. It's normally happen for unsupported provider. Please report the issue to our support team to let us support it: info@zzzprojects.com`

**Comment by JonathanMagnan** [comment] 2017-04-28 13:21
Hello @jrt324 ,

Are you using a special connection provider?

Can you paste the full name of your connection? Perhaps, that will help us to understand the issue.

```csharp
context.Database.Connection.GetType().FullName;
```

Best Regards,

Jonathan

**Comment by jrt324** [comment] 2017-05-04 02:54
@JonathanMagnan 
Strange thing is, when i update to  latest version, this problem did not appear

**Comment by JonathanMagnan** [comment] 2017-05-04 03:01
Jello @jrt324 ,

Which version were you using before? Perhaps we made a change that fixed it.

With your version, I could check our history so see what happened.

Best Regards,

Jonathan

**Comment by jrt324** [comment] 2017-05-04 03:36
Hello  @JonathanMagnan 
issue version is : 3.10.27

**Comment by JonathanMagnan** [comment] 2017-05-04 14:46
Thank you,

Way to many things has been modified since this version ;)

All operations now call a common method to get the destination, and we improved the logic since some time, Entity Framework model contains the wrong schema name depending on the provider.

I will close this issue since you confirmed that was fixed.

Best Regards,

Jonathan

**Closed by JonathanMagnan** 2017-05-04 14:46 UTC
