### ISSUE TITLE
Problem with tables with name "User" or "Group"

### ISSUE THREAD

**Issue by ChristofferBergkvist** [zzzprojects/EntityFramework-Extensions#13] opened 2016-08-23 06:12 UTC
Hi

I have a database with about 20 tables. Your library works great for all tables except two of them. These tables are called User and Group. When trying to bulk insert data into these I get this message:

An error occured while retrieving the InformationSchemaTable information.

However if I rename the tables and corresponing classes to UserX and GroupX everything seems to work fine.

Could it be because User and Group also are SQL keywords?

**Comment by ChristofferBergkvist** [comment] 2016-08-23 07:25
Hi again

I also have a table called Set which also did not work, same error.

**Comment by zzzprojects** [comment] 2016-08-23 13:44
Hello Christoffer,

You should have received a mail asking you to provide additional information.

Obviously, this error is due to using SQL keywords. However, we are not able to reproduce it under SQL Server.

**Comment by ChristofferBergkvist** [comment] 2016-08-23 14:00
Hi 

I saw you mail. I use version 3.10.1 and I am using sql ce 4.0 and EF6. I have not tested if it works in SQL server or not.

**Comment by zzzprojects** [comment] 2016-08-23 14:02
Thank you,

We will test with this provider and make sure the table name is escaped.

A new version should be available at the end of the day.

**Comment by zzzprojects** [comment] 2016-08-23 18:56
Hello Christoffer,

The v3.10.2 has been released.

The table name is now escaped for SQL Compact when retrieving table information.

Please, confirm us if the issue is resolved when you will try the latest version.

Best Regards,

Jonathan

**Comment by ChristofferBergkvist** [comment] 2016-08-24 07:28
Thanks, it worked :)

**Comment by zzzprojects** [comment] 2016-08-24 13:23
Closing: User confirmed the fix

**Closed by zzzprojects** 2016-08-24 13:23 UTC
