### ISSUE TITLE
Problem with bulk insert when class has a property with another class mapped with the EF Core OwnsOne

### ISSUE THREAD

**Issue by viniciusverasdossantos** [zzzprojects/EntityFramework-Extensions#396] opened 2021-02-18 11:48 UTC
### Description

I'm having problems with bulk insert when my class has a property with another class mapped with the EF Core OwnsOne method. The same class mapped with EF 6 works normally.

Classes:

```csharp
    public class PrecoDeVenda         
    { 
        public decimal Lucro { get; set; }
        public decimal CustoFinal { get; set; }  
        public decimal Preco { get; set; } 
    } 

   public class ProdutoFornecedor 
    {
 
        public ProdutoFornecedor() {  
            PrecoDeVenda = new PrecoDeVenda();
        }
 
        public Guid Id { get; set; }   
        public PrecoDeVenda PrecoDeVenda { get; set; }   
        public bool PossuiIpi { get; set; }
        public bool PossuiSubstituicaoTributaria { get; set; }
    }
```

Error in session.BulkInsert(registros);

Registros is List<ProdutoFornecedor>

ProdutoFornecedor is mapped in EF Core:

```csharp
public class ProdutoFornecedorDbMapping : IEntityTypeConfiguration<ProdutoFornecedor>
    {
        public void Configure(EntityTypeBuilder<ProdutoFornecedor> builder)
        {
            builder.HasKey(f => f.Id); 
            builder.OwnsOne(x => x.PrecoDeVenda, e => e.Property(e => e.AliquotaDeMargemDeLucro).HasPrecision(18, 4));
            builder.Navigation(x => x.PrecoDeVenda).IsRequired(); 
        }
    }
```

### Exception

Exception message:
Unable to cast object of type 'Vvs.CPlusAnywhere.Dominio.Produtos.Produtos.ProdutoFornecedor' to type 'Vvs.CPlusAnywhere.Dominio.Produtos.Precos.PrecosDeVenda.PrecoDeVenda'.

Stack trace: 
   at System.Runtime.CompilerServices.CastHelpers.ChkCastAny(Void* toTypeHnd, Object obj)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.ClrPropertyGetter`2.GetClrValue(Object entity)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.get_Item(IPropertyBase propertyBase)
   at .`1.( , String )
   at .( , DbConnection , DbTransaction )
   at .Execute(List`1 actions)
   at Z.BulkOperations.BulkOperation.Execute()
   at .BulkInsert[T](DbContext this, IEntityType entityType, IEnumerable`1 list, Action`1 options, SavingSelector savingSelector, Boolean forceSpecificTypeMapping)
   at .BulkInsert[T](DbContext this, IEnumerable`1 entities, Action`1 options, Boolean isBulkSaveChanges)
   at DbContextExtensions.BulkInsert[T](DbContext this, IEnumerable`1 entities, Action`1 options)
   at Vvs.Infraestrutura.Data.EFCore.EFCoreSession`1.BulkInsert[T](IEnumerable`1 entities)
   at Vvs.CPlusAnywhere.ConversorDeDados.Importacao.Core.Importador.<>c__DisplayClass256_0`1.<ExecutaImportacao>b__0() in C:\Fontes\Tfs\Projetos\Produtos\CPlus Anywhere\back-end\1-Dev\Dev\Aplicacao\ConversorDeDados\Importador.cs:line 6690
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)

### Further technical details
- EF version: EF Core 5.0.3
- EF Extensions version: 5.1.8
- Database Provider: npgsql 5.0.3

**Comment by JonathanMagnan** [comment] 2021-02-18 13:53
Hello @viniciusverasdossantos ,

Thank you for reporting, we will look at this.

The `OwnsOne` should be supported so it looks indeed like a bug.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment] 2021-02-22 17:26
Hello @viniciusverasdossantos ,

My developer tried it but he believes we are missing a missing piece of the puzzle to reproduce it.

Could you try his test and let him know what he is missing to reproduce this issue?

```csharp
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;

namespace lab.EFCore50.PostgreSQL
{
    public class Request_Owned
	{
		public static void Execute()
		{
			bool createAndDeleteBD = true;

			if (createAndDeleteBD)
			{
				// Create BD 
				using (var context = new EntityContext())
				{
					My.DeleteBD(context);
					context.Database.EnsureCreated();
				}
			}

			// CLEAN  
			using (var context = new EntityContext())
			{
				context.ProdutoFornecedors.RemoveRange(context.ProdutoFornecedors);

				context.SaveChanges();
			} 

			// TEST  
			using (var context = new EntityContext())
			{
				List<ProdutoFornecedor> list = new List<ProdutoFornecedor>();
				list.Add(new ProdutoFornecedor { Id = Guid.NewGuid() });
				list.Add(new ProdutoFornecedor { Id = Guid.NewGuid() });
				list.Add(new ProdutoFornecedor { Id = Guid.NewGuid() });
				list.Last().PrecoDeVenda.CustoFinal = 20;
				context.BulkInsert(list);
				var test = context.ProdutoFornecedors.ToList();
			}
		}

		public class EntityContext : DbContext
		{
			public EntityContext()
			{
			}

			public DbSet<ProdutoFornecedor> ProdutoFornecedors { get; set; }

			protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
			{
				optionsBuilder.UseNpgsql(My.Connection);
			}
			protected override void OnModelCreating(ModelBuilder builder)
			{
				builder.Entity<ProdutoFornecedor>().OwnsOne(x => x.PrecoDeVenda, e => e.Property(e => e.AliquotaDeMargemDeLucro).HasPrecision(18, 4));
				builder.Entity<ProdutoFornecedor>().Navigation(x => x.PrecoDeVenda).IsRequired();
			}
		}
		public class PrecoDeVenda
		{
			public decimal Lucro { get; set; } = 1;
			public decimal CustoFinal { get; set; } = 1;
			public decimal Preco { get; set; } = 1;
			public string AliquotaDeMargemDeLucro { get; set; }
		}

		public class ProdutoFornecedor
		{

			public ProdutoFornecedor()
			{
				PrecoDeVenda = new PrecoDeVenda();
			}

			public Guid Id { get; set; }
			public PrecoDeVenda PrecoDeVenda { get; set; }
			public bool PossuiIpi { get; set; }
			public bool PossuiSubstituicaoTributaria { get; set; }
		}
	}
}
```

**Comment by JonathanMagnan** [comment] 2021-02-25 14:05
Hello @viniciusverasdossantos ,

Since our last message, we haven't heard from you. 

As mentioned, my developer tried it but he believes we are missing a step to reproduce it.

Did you get the time to try his test?

Looking forward to hearing from you, 

Jon

**Comment by JonathanMagnan** [comment] 2021-03-04 13:51
Hello @viniciusverasdossantos ,

A simple reminder that we are here to assist you!

Don't hesitate to contact us once you try my developer test.

Looking forward to hearing from you,

Jon

**Comment by hgGeorg** [comment] 2021-06-15 14:15
Hello @JonathanMagnan ,
I've encountered the same issue.
Here is a minimal sample https://github.com/hgGeorg/bulk-sync-test/tree/complex-owned-types
This project also contains demos for my other reported issues. I can split them if needed.

**Comment by JonathanMagnan** [comment] 2021-06-15 15:14
Thank a lot @hgGeorg ,

My developer will look at it.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment] 2021-06-30 17:27
Hello @hgGeorg ,

A lot of improvement has been done for this issue.

Could you test the latest version and let us know if everything is working?

We currently only support some basic cases of owned one in another table. So we still not support some more complex scenario that involved multiple owned in another owned in another owned for example.

Best Regards,

Jon

**Comment by hgGeorg** [comment] 2021-07-01 10:07
Hello @JonathanMagnan ,

using my test project with EntityFramework-Extensions@5.2.0 still throws the same InvalidCastException: `Unable to cast object of type 'BulkSyncTest.Complex' to type 'BulkSyncTest.OwnedB'.`

Stacktrace:

```
   at System.Runtime.CompilerServices.CastHelpers.ChkCastAny(Void* toTypeHnd, Object obj)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.ClrPropertyGetter`2.GetClrValue(Object entity)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.ReadPropertyValue(IPropertyBase propertyBase)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.get_Item(IPropertyBase propertyBase)
   at .`1.( , String )
   at .GetValue(Int32 i)
   at Microsoft.Data.SqlClient.SqlBulkCopy.GetValueFromSourceRow(Int32 destRowIndex, Boolean& isSqlType, Boolean& isDataFeed, Boolean& isNull)
   at Microsoft.Data.SqlClient.SqlBulkCopy.ReadWriteColumnValueAsync(Int32 col)
   at Microsoft.Data.SqlClient.SqlBulkCopy.CopyColumnsAsync(Int32 col, TaskCompletionSource`1 source)
   at Microsoft.Data.SqlClient.SqlBulkCopy.CopyRowsAsync(Int32 rowsSoFar, Int32 totalRows, CancellationToken cts, TaskCompletionSource`1 source)
   at Microsoft.Data.SqlClient.SqlBulkCopy.CopyBatchesAsyncContinued(BulkCopySimpleResultSet internalResults, String updateBulkCommandText, CancellationToken cts, TaskCompletionSource`1 source)
   at Microsoft.Data.SqlClient.SqlBulkCopy.CopyBatchesAsync(BulkCopySimpleResultSet internalResults, String updateBulkCommandText, CancellationToken cts, TaskCompletionSource`1 source)
   at Microsoft.Data.SqlClient.SqlBulkCopy.WriteToServerInternalRestContinuedAsync(BulkCopySimpleResultSet internalResults, CancellationToken cts, TaskCompletionSource`1 source)
   at Microsoft.Data.SqlClient.SqlBulkCopy.WriteToServerInternalRestAsync(CancellationToken cts, TaskCompletionSource`1 source)
   at Microsoft.Data.SqlClient.SqlBulkCopy.WriteToServerInternalAsync(CancellationToken ctoken)
   at Microsoft.Data.SqlClient.SqlBulkCopy.WriteRowSourceToServerAsync(Int32 columnCount, CancellationToken ctoken)
   at Microsoft.Data.SqlClient.SqlBulkCopy.WriteToServer(IDataReader reader)
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid2[T0,T1](CallSite site, T0 arg0, T1 arg1)
   at .( , DbConnection , DbTransaction , Int32 )
   at .( )
   at .( )
   at .Execute(List`1 actions)
   at .(List`1 )
   at Z.BulkOperations.BulkOperation.Execute()
   at .BulkSynchronize[T](DbContext this, IEntityType entityType, IEnumerable`1 list, Action`1 options, Boolean forceSpecificTypeMapping)
   at .BulkSynchronize[T](DbContext this, IEnumerable`1 entities, Action`1 options)
   at BulkSyncTest.ComplexModel.Demo(MyDbContext context, MyDbContext syncContext) in C:\Users\hgGeorg\source\repos\BulkSyncTest\BulkSyncTest\ComplexModel.cs:line 24
```

Please feel free to use my demo project as you see fit.

**Comment by JonathanMagnan** [comment] 2021-07-02 17:13
Thank you for letting me know,

I will re-assign this issue with my developer and double-check with him to make sure the demo work.

Best Regards,

Jon

**Comment by hgGeorg** [comment] 2021-07-20 13:39
Hello @JonathanMagnan ,

do you have any updates on this issue? We'd like to have a bit more information or a rough estimate to plan our own development and business.

Best regards,
Georg

**Comment by JonathanMagnan** [comment] 2021-07-20 23:59
Hello @hgGeorg ,

Sorry for the delay, we mixed both of your requests together and forget to answer you this one.

The fix for this issue has already been released.

I had to modify a little bit your demo since the `Reference` class is not part of the entity but using the latest version, everything was working:

```csharp
public static void Demo(MyDbContext context, MyDbContext syncContext)
{
	context.RemoveRange(context.ComplexTypes);
	context.SaveChanges();

	if (!context.ComplexTypes.Any())
	{
		context.ComplexTypes.Add(new Complex
		{
			OwnedA = new OwnedA
			{
				Referenced = new Referenced()
			},
			OwnedB = new OwnedB() {  Content = "z1"}
		});
		context.SaveChanges();
	}
	try
	{
		syncContext.BulkInsert(context.ComplexTypes.Select(x => x.OwnedA.Referenced), options => options.InsertKeepIdentity = true);

		syncContext.BulkSynchronize(context.ComplexTypes.AsNoTracking(), options =>
		{
			options.SynchronizeKeepidentity = true;
		});
	}
	catch (Exception exc)
	{ 
		// relevant for this bug report
		Console.WriteLine(exc);
	}
}
```

Let me know if everything is fixed here.

**Comment by hgGeorg** [comment] 2021-07-21 09:59
Preliminary tests look promising. Issue seems to be fixed. Thank you.

**Comment by JonathanMagnan** [comment] 2021-07-21 12:07
Awesome @hgGeorg ,

We are glad to hear that the issue has been fixed!

Don't hesitate to contact us with any questions, issues, or feedback!

Best regards,

Jon

**Closed by JonathanMagnan** 2021-07-21 12:07 UTC
