### ISSUE TITLE
BulkInsert Error in Version 8.0.0-preview.7.23375.4-01

### ISSUE THREAD

**Issue by viniciusverasdossantos** [zzzprojects/EntityFramework-Extensions#540] opened 2023-09-03 04:57 UTC
### Description
In some entities, the error below is occurring when executing bulk insert
Do you have any updates for this?
Is there somewhere that has documentation regarding class options BulkOperation ?
Action<BulkOperation<TDestino>> operation = b =>
{
    b.AutoMapOutputDirection = false; 
};
session.BulkInsert(registros, operation);

### Exception
   at ..ctor(EntityTypeZInfo , ISkipNavigation )
   at Z.EntityFramework.Extensions.EntityTypeZInfo.(ISkipNavigation )
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
   at Z.EntityFramework.Extensions.EntityTypeZInfo.()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at .( )
   at .Execute()
   at .()
   at .Create()
   at .Create(DbContext context, EntityTypeZInfo entityTypeInfo, IEqualityComparer`1 dictionaryEqualityComparer, List`1 list, BulkOperationActionType actionType, Boolean isIncludGraph, Boolean isIncludGraphBuilderBulkSaveChanges)
   at .BulkInsert[T](DbContext this, IEnumerable`1 entities, Action`1 options, Boolean isBulkSaveChanges)
   at DbContextExtensions.BulkInsert[T](DbContext this, IEnumerable`1 entities, Action`1 options)
   at Vvs.CPlusAnywhere.ConversorDeDados.Importacao.Core.Importador.<>c__DisplayClass271_0`1.<ExecutaImportacao>b__0() in C:\repos\CPlus5\Aplicacao\ConversorDeDados\Importador.cs:line 7342

```
Exception message:
Stack trace:
```
### Further technical details
- EF version: 8.0.0-preview.7
- EF Extensions version: 8.0.0-preview.7.23375.4-01
- Database Provider: 8.0.0-preview.7

**Comment by JonathanMagnan** [comment] 2023-09-04 12:49
Hello @viniciusverasdossantos ,

Do you think you could create a runnable project with the issue? It doesn’t need to be your project, just a new solution with the minimum code to reproduce the issue. You can also send it in private here: info@zzzprojects.com

That is definitely something we would like to fix but we currently don't know how to reproduce this issue as this is not an expected error.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment] 2023-09-13 13:26
Hello again, 

A simple reminder that we are here to assist you. 

Don't hesitate to contact us if you need further assistance.

Best regards, 
Jon

**Comment by viniciusverasdossantos** [comment] 2023-09-13 23:06
Thanks, I'll try again when the version compatible with RC1 comes out

**Comment by viniciusverasdossantos** [comment] 2023-09-17 11:36
Are there plans to release a version compatible with RC1?

**Comment by JonathanMagnan** [comment] 2023-09-18 13:36
Hello @viniciusverasdossantos ,

The RC1 will be released tomorrow.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment] 2023-09-19 22:11
Hello @viniciusverasdossantos ,

The new version has been released today supporting RC1: https://www.nuget.org/packages/Z.EntityFramework.Extensions.EFCore/8.0.0-rc.1.23419.6-01

If it still fails, I highly suggest you try to create a runnable project so we can look at this issue.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment] 2023-10-02 18:52
Hello @viniciusverasdossantos, 

Since our last conversation, we haven't heard from you. 

Let me know if you need more information. 

Best regards,
Jon

**Closed** 2023-10-09 13:32 UTC
