### ISSUE TITLE
BulkInsert fails with TypeInitializationException exception

### ISSUE THREAD

**Issue by mmiller678** [zzzprojects/EntityFramework-Extensions#91] opened 2018-04-02 21:02 UTC
This is using EF Core 2.1 Preview.  Any ideas on where to start looking for issues?

System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for '' threw an exception.
  Source=Z.EntityFramework.Extensions.EFCore
  StackTrace:
   at .[](DbContext this, IEnumerable`1 , Action`1 )
   at Data.Repositories.Data.DataValueRepository.BulkInsert(ICollection`1 values) in 
** FULL STACK TRACE SOURCE REMOVED **
Inner Exception 1:
ArgumentException: Expression of type 'System.Collections.Generic.IReadOnlyList`1[Microsoft.EntityFrameworkCore.Update.IUpdateEntry]' cannot be used for return type 'System.Collections.Generic.List`1[Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry]'

**Comment by tedypranolo** [comment] 2018-04-03 01:01
I was just about to report the same exact thing. It's also happening to BulkSaveChanges.

**Comment by JonathanMagnan** [comment] 2018-04-03 01:25
Hello @mmiller678  and @tedypranolo ,

Thank you for reporting it, we will check what has been changed in EF Core 2.1 Preview.

It should be fixed tomorrow.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment] 2018-04-03 18:18
Hello @mmiller678 , @tedypranolo ,

The v2.1.4 has been released.

The new version should now be compatible with EF Core 2.1 Preview.

Let me know if we missed something.

Best Regards,

Jonathan

**Comment by tedypranolo** [comment] 2018-04-04 02:53
I think it's been fixed, I no longer get that exception. However I'm running into a different issue with BulkInsert. See #92

**Comment by xalhera** [comment] 2019-04-17 07:21
Hi there,

Unfortunately I'm facing the same issue during Bulk Operations but only with Unit Tests on SQLite InMemory Database.
Everything works well in Debug Mode on SQL Server Database.

### Environment

.Net Core Runtime : 2.2.203

Package | Version
------------- | -------------
Microsoft.NETCore.App | 2.2.0
Microsoft.EntityFrameworkCore | 2.2.4
Z.EntityFramework.Extensions.EFCore | 2.2.3
Microsoft.EntityFrameworkCore.Sqlite | 3.0.0-preview.19074.3

### Exception
**Source :** `Z.EntityFramework.Extensions.EFCore`
**Message :** `The type initializer for '<' threw an exception.`
**StackTrace :**
```
   at <.(DbContext this, IEnumerable`1 , Action`1 )
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at DbContextExtensions.BulkUpdateAsync[T](DbContext this, IEnumerable`1 entities, Action`1 options, CancellationToken cancellationToken)
   at *** PRIVATE INFOS ***
```
**InnerException :**
&nbsp;&nbsp;&nbsp;&nbsp;**Message :** `Object reference not set to an instance of an object.`
&nbsp;&nbsp;&nbsp;&nbsp;**StackTrace :** `   at <..cctor()`

**Comment by JonathanMagnan** [comment] 2019-04-17 23:37
Hello @xalhera ,

It could be as you are currently using a v3.x and no test on our side has been done yet on this version.

We will look at it.

Best Regards,

Jonathan

**Comment by xalhera** [comment] 2019-04-18 06:38
For some reason the v3.x is a mandatory in my case.

Indeed, the issue is thrown because of the Microsoft.EntityFrameworkCore.Sqlite package preview version.

Please let me know if you plan to fix this.

Sincerly

**Comment by JonathanMagnan** [comment] 2019-04-18 08:39
Yup,

My employee will look at it today and we will check what has been modified in this version

**Comment by JonathanMagnan** [comment] 2019-04-18 17:24
Hello @xalhera ,

We started to look at it and the v3.x has some major code modification that's currently not compatible with our code.

It will take longer than we first expected but we will continue to look at it next week and will keep you informed.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment] 2019-04-30 14:45
Hello @xalhera ,

Could you try the latest version (v2.2.5)?

We started to support EF Core v3.x preview4,

Let me know if you find any issue with this version. There is some major change on their side, we there is good chance we might have missed something.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment] 2019-05-12 23:04
Hello @xalhera ,

Do you have any news about it? Did you got the time to try it?

**Comment by xalhera** [comment] 2019-05-20 22:36
Hi @JonathanMagnan,

The tests succeeded with the following packages :

| Package | Version |
| -- | -- |
| Z.EntityFramework.Extensions.EFCore | 2.2.8 |
| Microsoft.EntityFrameworkCore.Sqlite | 3.0.0-preview.19074.3 |

Thanks a lot for your job, you did a great one !

**Comment by JonathanMagnan** [comment] 2019-05-21 01:06
Great ;)

**Closed by JonathanMagnan** 2019-05-21 01:06 UTC

**Comment by vilijatr** [comment] 2021-12-21 08:46
We started getting the same after project upgrade to dotnet 6 (the only change I can pinpoint, nothing else was changed).

**Comment by JonathanMagnan** [comment] 2021-12-22 00:06
Hello @vilijatr ,

Do you think you could create a runnable project with the issue? It doesn’t need to be your project, just a new solution with the minimum code to reproduce the issue. You can send it in private here: info@zzzprojects.com

Best Regards,

Jon
