### ISSUE TITLE
Exception in BulkSaveChanges

### ISSUE THREAD

**Issue by rworbis** [zzzprojects/EntityFramework-Extensions#67] opened 2017-12-07 06:13 UTC
Hello, when doing a BulkSaveChanges we get the following Exception:

```
Incorrect syntax near the keyword 'INTO'.
Incorrect syntax near the keyword 'AS'.

   at Z.EntityFramework.Extensions.SqlServerBulkSaveChanges.()
   at DbContextExtensions.(DbContext , Boolean , Action`1 , Boolean )
   at DbContextExtensions.BulkSaveChanges(DbContext this, Boolean useEntityFrameworkPropagation, Action`1 bulkOperationFactory)
   at DbContextExtensions.BulkSaveChanges(DbContext this)

   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet)
   at Z.Data.SqlClient.SqlCommandSet.Execute()
   at Z.BulkOperations.DbActionExecutor.(DbConnection , DbTransaction , List`1 )
   at Z.EntityFramework.Extensions.SqlServerBulkSaveChanges.()
```

Here is the profiler output from the sql server: (the second block seems to be the problem)

```sql
exec sp_executesql N'MERGE INTO [dbo].[AR_Queue] AS DestinationTable
USING
(
SELECT @0_0_0 AS [QueueDatum], @0_0_1 AS [BerichtId], @0_0_2 AS [BerichtGruppeId], @0_0_3 AS [Aktiv], @0_0_4 AS [StartDatum], @0_0_5 AS [EndDatum], @0_0_6 AS [Prioritaet], @0_0_7 AS [Beschreibung], @0_0_8 AS [ExternalQueueId], @0_0_9 AS [ErsetzeBenutzervariablen], @0_0_10 AS [QueueParameterBefuellen], @0_0_11 AS [HistorieId], @0_0_12 AS [BearbeitetAm], @0_0_13 AS [BearbeitetVon], @0_0_14 AS [ErstelltAm], @0_0_15 AS [ErstelltVon], @0_0_16 AS ZZZPredicate_75feb21112034aa49685fc91634cdbbe, @0_0_17 AS ZZZ_Index
) AS StagingTable
ON DestinationTable.[QueueId] = StagingTable.ZZZPredicate_75feb21112034aa49685fc91634cdbbe
WHEN MATCHED   THEN
    UPDATE
    SET     [QueueDatum] = StagingTable.[QueueDatum], [BerichtId] = StagingTable.[BerichtId], [BerichtGruppeId] = StagingTable.[BerichtGruppeId], [Aktiv] = StagingTable.[Aktiv], [StartDatum] = StagingTable.[StartDatum], [EndDatum] = StagingTable.[EndDatum], [Prioritaet] = StagingTable.[Prioritaet], [Beschreibung] = StagingTable.[Beschreibung], [ExternalQueueId] = StagingTable.[ExternalQueueId], [ErsetzeBenutzervariablen] = StagingTable.[ErsetzeBenutzervariablen], [QueueParameterBefuellen] = StagingTable.[QueueParameterBefuellen], [HistorieId] = StagingTable.[HistorieId], [BearbeitetAm] = StagingTable.[BearbeitetAm], [BearbeitetVon] = StagingTable.[BearbeitetVon], [ErstelltAm] = StagingTable.[ErstelltAm], [ErstelltVon] = StagingTable.[ErstelltVon]
;
MERGE INTO [dbo].[AR_QueueParameter] AS DestinationTable
USING
(
SELECT @1_0_0 AS [QueueId], @1_0_1 AS [BerichtId], @1_0_2 AS [Laufnummer], @1_0_3 AS [ParameterName], @1_0_4 AS [ParameterWert], @1_0_5 AS [BearbeitetAm], @1_0_6 AS [BearbeitetVon], @1_0_7 AS [ErstelltAm], @1_0_8 AS [ErstelltVon], @1_0_9 AS ZZZPredicate_fa2f9e2a6563452fb66e37a3e8192f5e, @1_0_10 AS ZZZ_Index
UNION ALL SELECT @1_1_0 AS [QueueId], @1_1_1 AS [BerichtId], @1_1_2 AS [Laufnummer], @1_1_3 AS [ParameterName], @1_1_4 AS [ParameterWert], @1_1_5 AS [BearbeitetAm], @1_1_6 AS [BearbeitetVon], @1_1_7 AS [ErstelltAm], @1_1_8 AS [ErstelltVon], @1_1_9 AS ZZZPredicate_fa2f9e2a6563452fb66e37a3e8192f5e, @1_1_10 AS ZZZ_Index
) AS StagingTable
ON DestinationTable.[QueueParameterId] = StagingTable.ZZZPredicate_fa2f9e2a6563452fb66e37a3e8192f5e
WHEN MATCHED   THEN
    UPDATE
    SET     [QueueId] = StagingTable.[QueueId], [BerichtId] = StagingTable.[BerichtId], [Laufnummer] = StagingTable.[Laufnummer], [ParameterName] = StagingTable.[ParameterName], [ParameterWert] = StagingTable.[ParameterWert], [BearbeitetAm] = StagingTable.[BearbeitetAm], [BearbeitetVon] = StagingTable.[BearbeitetVon], [ErstelltAm] = StagingTable.[ErstelltAm], [ErstelltVon] = StagingTable.[ErstelltVon]
;
',N'@0_0_0 datetime,@0_0_1 int,@0_0_2 int,@0_0_3 bit,@0_0_4 datetime,@0_0_5 datetime,@0_0_6 int,@0_0_7 varchar(max) ,@0_0_8 int,@0_0_9 bit,@0_0_10 bit,@0_0_11 int,@0_0_12 datetime,@0_0_13 varchar(50),@0_0_14 datetime,@0_0_15 varchar(50),@0_0_16 int,@0_0_17 int,@1_0_0 int,@1_0_1 int,@1_0_2 int,@1_0_3 varchar(100),@1_0_4 varchar(max) ,@1_0_5 datetime,@1_0_6 varchar(50),@1_0_7 datetime,@1_0_8 varchar(50),@1_0_9 int,@1_0_10 int,@1_1_0 int,@1_1_1 int,@1_1_2 int,@1_1_3 varchar(100),@1_1_4 varchar(max) ,@1_1_5 datetime,@1_1_6 varchar(50),@1_1_7 datetime,@1_1_8 varchar(50),@1_1_9 int,@1_1_10 int',@0_0_0='2017-12-07 06:59:57.493',@0_0_1=432,@0_0_2=NULL,@0_0_3=0,@0_0_4='2017-12-07 07:10:45.223',@0_0_5='2017-12-07 07:10:45.223',@0_0_6=1,@0_0_7=NULL,@0_0_8=NULL,@0_0_9=0,@0_0_10=NULL,@0_0_11=NULL,@0_0_12='2017-12-07 06:59:57.493',@0_0_13='r.worbis',@0_0_14='2017-12-07 06:59:57.493',@0_0_15='r.worbis',@0_0_16=1097,@0_0_17=0,@1_0_0=1097,@1_0_1=432,@1_0_2=1,@1_0_3='UserID',@1_0_4='2121',@1_0_5='2017-12-07 07:10:45.190',@1_0_6='SYSTEM',@1_0_7='2017-12-07 06:59:57.503',@1_0_8='r.worbis',@1_0_9=126098,@1_0_10=0,@1_1_0=1097,@1_1_1=432,@1_1_2=1,@1_1_3='UserEMail',@1_1_4='r.worbis@cubido.at',@1_1_5='2017-12-07 07:10:45.190',@1_1_6='SYSTEM',@1_1_7='2017-12-07 06:59:57.510',@1_1_8='r.worbis',@1_1_9=126099,@1_1_10=1
go
exec sp_executesql N'CREATE TABLE #ZZZProjects_81c0c488_139f_4aa3_ad74_01ff555f1f91z ( [$action] VARCHAR(100) NULL, ZZZ_Index INT NULL, [QueueId_zzzinserted] [sys].[int] NULL )
MERGE INTO [dbo].[AR_Queue] AS DestinationTable
USING
(
SELECT @0_0_0 AS [QueueDatum], @0_0_1 AS [BerichtId], @0_0_2 AS [BerichtGruppeId], @0_0_3 AS [Aktiv], @0_0_4 AS [StartDatum], @0_0_5 AS [EndDatum], @0_0_6 AS [Prioritaet], @0_0_7 AS [Beschreibung], @0_0_8 AS [ExternalQueueId], @0_0_9 AS [ErsetzeBenutzervariablen], @0_0_10 AS [QueueParameterBefuellen], @0_0_11 AS [HistorieId], @0_0_12 AS [BearbeitetAm], @0_0_13 AS [BearbeitetVon], @0_0_14 AS [ErstelltAm], @0_0_15 AS [ErstelltVon], @0_0_16 AS ZZZ_Index
UNION ALL SELECT @0_1_0 AS [QueueDatum], @0_1_1 AS [BerichtId], @0_1_2 AS [BerichtGruppeId], @0_1_3 AS [Aktiv], @0_1_4 AS [StartDatum], @0_1_5 AS [EndDatum], @0_1_6 AS [Prioritaet], @0_1_7 AS [Beschreibung], @0_1_8 AS [ExternalQueueId], @0_1_9 AS [ErsetzeBenutzervariablen], @0_1_10 AS [QueueParameterBefuellen], @0_1_11 AS [HistorieId], @0_1_12 AS [BearbeitetAm], @0_1_13 AS [BearbeitetVon], @0_1_14 AS [ErstelltAm], @0_1_15 AS [ErstelltVon], @0_1_16 AS ZZZ_Index
) AS StagingTable
ON 1 = 2
WHEN NOT MATCHED THEN
    INSERT ( [QueueDatum], [BerichtId], [BerichtGruppeId], [Aktiv], [StartDatum], [EndDatum], [Prioritaet], [Beschreibung], [ExternalQueueId], [ErsetzeBenutzervariablen], [QueueParameterBefuellen], [HistorieId], [BearbeitetAm], [BearbeitetVon], [ErstelltAm], [ErstelltVon] )
    VALUES ( [QueueDatum], [BerichtId], [BerichtGruppeId], [Aktiv], [StartDatum], [EndDatum], [Prioritaet], [Beschreibung], [ExternalQueueId], [ErsetzeBenutzervariablen], [QueueParameterBefuellen], [HistorieId], [BearbeitetAm], [BearbeitetVon], [ErstelltAm], [ErstelltVon] )
OUTPUT
    $action,
    StagingTable.ZZZ_Index,
    INSERTED.[QueueId] AS [QueueId_zzzinserted]
INTO #ZZZProjects_81c0c488_139f_4aa3_ad74_01ff555f1f91z
;
SELECT * FROM #ZZZProjects_81c0c488_139f_4aa3_ad74_01ff555f1f91z
DROP TABLE #ZZZProjects_81c0c488_139f_4aa3_ad74_01ff555f1f91z
',N'@0_0_0 datetime,@0_0_1 int,@0_0_2 int,@0_0_3 bit,@0_0_4 datetime,@0_0_5 datetime,@0_0_6 int,@0_0_7 varchar(max) ,@0_0_8 int,@0_0_9 bit,@0_0_10 bit,@0_0_11 int,@0_0_12 datetime,@0_0_13 varchar(50),@0_0_14 datetime,@0_0_15 varchar(50),@0_0_16 int,@0_1_0 datetime,@0_1_1 int,@0_1_2 int,@0_1_3 bit,@0_1_4 datetime,@0_1_5 datetime,@0_1_6 int,@0_1_7 varchar(max) ,@0_1_8 int,@0_1_9 bit,@0_1_10 bit,@0_1_11 int,@0_1_12 datetime,@0_1_13 varchar(50),@0_1_14 datetime,@0_1_15 varchar(50),@0_1_16 int',@0_0_0='2017-12-07 07:10:45.017',@0_0_1=432,@0_0_2=NULL,@0_0_3=1,@0_0_4=NULL,@0_0_5=NULL,@0_0_6=1,@0_0_7='Mail=r.worbis@cubido.at;Jahr=2005;',@0_0_8=NULL,@0_0_9=0,@0_0_10=NULL,@0_0_11=NULL,@0_0_12='2017-12-07 07:10:45.017',@0_0_13='SYSTEM',@0_0_14='2017-12-07 07:10:45.017',@0_0_15='SYSTEM',@0_0_16=0,@0_1_0='2017-12-07 07:10:45.127',@0_1_1=432,@0_1_2=NULL,@0_1_3=1,@0_1_4=NULL,@0_1_5=NULL,@0_1_6=1,@0_1_7='Mail=r.worbis@cubido.at;Jahr=2006;',@0_1_8=NULL,@0_1_9=0,@0_1_10=NULL,@0_1_11=NULL,@0_1_12='2017-12-07 07:10:45.127',@0_1_13='SYSTEM',@0_1_14='2017-12-07 07:10:45.127',@0_1_15='SYSTEM',@0_1_16=1
go
```

**Comment by JonathanMagnan** [comment] 2017-12-07 14:06
Hello @rworbis ,

Thank you for reporting, we will look at it today.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment] 2017-12-07 18:44
Hello @rworbis ,

We started to investigate this issue but unfortunately, we were not able to reproduce it.

- We verified the SQL and everything seem valid
- We created a similar table as your and run successfully the SQL

Looking at the strategy taken by our library, we believe your table has some trigger. Is it possible to provide us these triggers? info@zzzprojects.com

Also, do you think you could try the following SQL in your environment? Just to make sure we have not missed something here.

```sql
CREATE TABLE [dbo].[AR_Queue](
	[QueueId] [INT] IDENTITY(1,1) NOT NULL,
	[QueueDatum] [DATETIME2](7) NOT NULL,
	[BerichtId] [INT] NULL,
	[BerichtGruppeId] [INT] NULL,
	[Aktiv] [BIT] NULL,
	[StartDatum] [DATETIME2](7) NULL,
	[EndDatum] [DATETIME2](7) NULL,
	[Prioritaet] [INT] NULL,
	[Beschreibung] [VARCHAR](MAX) NULL,
	[ExternalQueueId] [INT] NULL,
	[ErsetzeBenutzervariablen] [BIT] NULL,
	[QueueParameterBefuellen] [BIT] NULL,
	[HistorieId] [INT] NULL,
	[BearbeitetAm] [DATETIME2](7) NULL,
	[BearbeitetVon] [VARCHAR](50) NULL,
	[ErstelltAm] [DATETIME2](7) NULL,
	[ErstelltVon] [VARCHAR](50) NULL,
)

CREATE TABLE [dbo].[AR_QueueParameter](
	[QueueParameterId] [INT] IDENTITY(1,1) NOT NULL,
	[QueueId] [INT] NULL,
	[BerichtId] [INT] NULL,
	[Laufnummer] [INT] NULL,
	[ParameterName] [VARCHAR](100) NULL,
	[ParameterWert] [VARCHAR](MAX) NULL,
	[BearbeitetAm] [DATETIME] NULL,
	[BearbeitetVon] [VARCHAR](50) NULL,
	[ErstelltAm] [DATETIME] NULL,
	[ErstelltVon] [VARCHAR](50) NULL
)

exec sp_executesql N'MERGE INTO [dbo].[AR_Queue] AS DestinationTable
USING
(
SELECT @0_0_0 AS [QueueDatum], @0_0_1 AS [BerichtId], @0_0_2 AS [BerichtGruppeId], @0_0_3 AS [Aktiv], @0_0_4 AS [StartDatum], @0_0_5 AS [EndDatum], @0_0_6 AS [Prioritaet], @0_0_7 AS [Beschreibung], @0_0_8 AS [ExternalQueueId], @0_0_9 AS [ErsetzeBenutzervariablen], @0_0_10 AS [QueueParameterBefuellen], @0_0_11 AS [HistorieId], @0_0_12 AS [BearbeitetAm], @0_0_13 AS [BearbeitetVon], @0_0_14 AS [ErstelltAm], @0_0_15 AS [ErstelltVon], @0_0_16 AS ZZZPredicate_75feb21112034aa49685fc91634cdbbe, @0_0_17 AS ZZZ_Index
) AS StagingTable
ON DestinationTable.[QueueId] = StagingTable.ZZZPredicate_75feb21112034aa49685fc91634cdbbe
WHEN MATCHED   THEN
    UPDATE
    SET     [QueueDatum] = StagingTable.[QueueDatum], [BerichtId] = StagingTable.[BerichtId], [BerichtGruppeId] = StagingTable.[BerichtGruppeId], [Aktiv] = StagingTable.[Aktiv], [StartDatum] = StagingTable.[StartDatum], [EndDatum] = StagingTable.[EndDatum], [Prioritaet] = StagingTable.[Prioritaet], [Beschreibung] = StagingTable.[Beschreibung], [ExternalQueueId] = StagingTable.[ExternalQueueId], [ErsetzeBenutzervariablen] = StagingTable.[ErsetzeBenutzervariablen], [QueueParameterBefuellen] = StagingTable.[QueueParameterBefuellen], [HistorieId] = StagingTable.[HistorieId], [BearbeitetAm] = StagingTable.[BearbeitetAm], [BearbeitetVon] = StagingTable.[BearbeitetVon], [ErstelltAm] = StagingTable.[ErstelltAm], [ErstelltVon] = StagingTable.[ErstelltVon]
;
MERGE INTO [dbo].[AR_QueueParameter] AS DestinationTable
USING
(
SELECT @1_0_0 AS [QueueId], @1_0_1 AS [BerichtId], @1_0_2 AS [Laufnummer], @1_0_3 AS [ParameterName], @1_0_4 AS [ParameterWert], @1_0_5 AS [BearbeitetAm], @1_0_6 AS [BearbeitetVon], @1_0_7 AS [ErstelltAm], @1_0_8 AS [ErstelltVon], @1_0_9 AS ZZZPredicate_fa2f9e2a6563452fb66e37a3e8192f5e, @1_0_10 AS ZZZ_Index
UNION ALL SELECT @1_1_0 AS [QueueId], @1_1_1 AS [BerichtId], @1_1_2 AS [Laufnummer], @1_1_3 AS [ParameterName], @1_1_4 AS [ParameterWert], @1_1_5 AS [BearbeitetAm], @1_1_6 AS [BearbeitetVon], @1_1_7 AS [ErstelltAm], @1_1_8 AS [ErstelltVon], @1_1_9 AS ZZZPredicate_fa2f9e2a6563452fb66e37a3e8192f5e, @1_1_10 AS ZZZ_Index
) AS StagingTable
ON DestinationTable.[QueueParameterId] = StagingTable.ZZZPredicate_fa2f9e2a6563452fb66e37a3e8192f5e
WHEN MATCHED   THEN
    UPDATE
    SET     [QueueId] = StagingTable.[QueueId], [BerichtId] = StagingTable.[BerichtId], [Laufnummer] = StagingTable.[Laufnummer], [ParameterName] = StagingTable.[ParameterName], [ParameterWert] = StagingTable.[ParameterWert], [BearbeitetAm] = StagingTable.[BearbeitetAm], [BearbeitetVon] = StagingTable.[BearbeitetVon], [ErstelltAm] = StagingTable.[ErstelltAm], [ErstelltVon] = StagingTable.[ErstelltVon]
;
',N'@0_0_0 datetime,@0_0_1 int,@0_0_2 int,@0_0_3 bit,@0_0_4 datetime,@0_0_5 datetime,@0_0_6 int,@0_0_7 varchar(max) ,@0_0_8 int,@0_0_9 bit,@0_0_10 bit,@0_0_11 int,@0_0_12 datetime,@0_0_13 varchar(50),@0_0_14 datetime,@0_0_15 varchar(50),@0_0_16 int,@0_0_17 int,@1_0_0 int,@1_0_1 int,@1_0_2 int,@1_0_3 varchar(100),@1_0_4 varchar(max) ,@1_0_5 datetime,@1_0_6 varchar(50),@1_0_7 datetime,@1_0_8 varchar(50),@1_0_9 int,@1_0_10 int,@1_1_0 int,@1_1_1 int,@1_1_2 int,@1_1_3 varchar(100),@1_1_4 varchar(max) ,@1_1_5 datetime,@1_1_6 varchar(50),@1_1_7 datetime,@1_1_8 varchar(50),@1_1_9 int,@1_1_10 int',@0_0_0='2017-12-07 06:59:57.493',@0_0_1=432,@0_0_2=NULL,@0_0_3=0,@0_0_4='2017-12-07 07:10:45.223',@0_0_5='2017-12-07 07:10:45.223',@0_0_6=1,@0_0_7=NULL,@0_0_8=NULL,@0_0_9=0,@0_0_10=NULL,@0_0_11=NULL,@0_0_12='2017-12-07 06:59:57.493',@0_0_13='r.worbis',@0_0_14='2017-12-07 06:59:57.493',@0_0_15='r.worbis',@0_0_16=1097,@0_0_17=0,@1_0_0=1097,@1_0_1=432,@1_0_2=1,@1_0_3='UserID',@1_0_4='2121',@1_0_5='2017-12-07 07:10:45.190',@1_0_6='SYSTEM',@1_0_7='2017-12-07 06:59:57.503',@1_0_8='r.worbis',@1_0_9=126098,@1_0_10=0,@1_1_0=1097,@1_1_1=432,@1_1_2=1,@1_1_3='UserEMail',@1_1_4='r.worbis@cubido.at',@1_1_5='2017-12-07 07:10:45.190',@1_1_6='SYSTEM',@1_1_7='2017-12-07 06:59:57.510',@1_1_8='r.worbis',@1_1_9=126099,@1_1_10=1
go
exec sp_executesql N'CREATE TABLE #ZZZProjects_81c0c488_139f_4aa3_ad74_01ff555f1f91z ( [$action] VARCHAR(100) NULL, ZZZ_Index INT NULL, [QueueId_zzzinserted] [sys].[int] NULL )
MERGE INTO [dbo].[AR_Queue] AS DestinationTable
USING
(
SELECT @0_0_0 AS [QueueDatum], @0_0_1 AS [BerichtId], @0_0_2 AS [BerichtGruppeId], @0_0_3 AS [Aktiv], @0_0_4 AS [StartDatum], @0_0_5 AS [EndDatum], @0_0_6 AS [Prioritaet], @0_0_7 AS [Beschreibung], @0_0_8 AS [ExternalQueueId], @0_0_9 AS [ErsetzeBenutzervariablen], @0_0_10 AS [QueueParameterBefuellen], @0_0_11 AS [HistorieId], @0_0_12 AS [BearbeitetAm], @0_0_13 AS [BearbeitetVon], @0_0_14 AS [ErstelltAm], @0_0_15 AS [ErstelltVon], @0_0_16 AS ZZZ_Index
UNION ALL SELECT @0_1_0 AS [QueueDatum], @0_1_1 AS [BerichtId], @0_1_2 AS [BerichtGruppeId], @0_1_3 AS [Aktiv], @0_1_4 AS [StartDatum], @0_1_5 AS [EndDatum], @0_1_6 AS [Prioritaet], @0_1_7 AS [Beschreibung], @0_1_8 AS [ExternalQueueId], @0_1_9 AS [ErsetzeBenutzervariablen], @0_1_10 AS [QueueParameterBefuellen], @0_1_11 AS [HistorieId], @0_1_12 AS [BearbeitetAm], @0_1_13 AS [BearbeitetVon], @0_1_14 AS [ErstelltAm], @0_1_15 AS [ErstelltVon], @0_1_16 AS ZZZ_Index
) AS StagingTable
ON 1 = 2
WHEN NOT MATCHED THEN
    INSERT ( [QueueDatum], [BerichtId], [BerichtGruppeId], [Aktiv], [StartDatum], [EndDatum], [Prioritaet], [Beschreibung], [ExternalQueueId], [ErsetzeBenutzervariablen], [QueueParameterBefuellen], [HistorieId], [BearbeitetAm], [BearbeitetVon], [ErstelltAm], [ErstelltVon] )
    VALUES ( [QueueDatum], [BerichtId], [BerichtGruppeId], [Aktiv], [StartDatum], [EndDatum], [Prioritaet], [Beschreibung], [ExternalQueueId], [ErsetzeBenutzervariablen], [QueueParameterBefuellen], [HistorieId], [BearbeitetAm], [BearbeitetVon], [ErstelltAm], [ErstelltVon] )
OUTPUT
    $action,
    StagingTable.ZZZ_Index,
    INSERTED.[QueueId] AS [QueueId_zzzinserted]
INTO #ZZZProjects_81c0c488_139f_4aa3_ad74_01ff555f1f91z
;
SELECT * FROM #ZZZProjects_81c0c488_139f_4aa3_ad74_01ff555f1f91z
DROP TABLE #ZZZProjects_81c0c488_139f_4aa3_ad74_01ff555f1f91z
',N'@0_0_0 datetime,@0_0_1 int,@0_0_2 int,@0_0_3 bit,@0_0_4 datetime,@0_0_5 datetime,@0_0_6 int,@0_0_7 varchar(max) ,@0_0_8 int,@0_0_9 bit,@0_0_10 bit,@0_0_11 int,@0_0_12 datetime,@0_0_13 varchar(50),@0_0_14 datetime,@0_0_15 varchar(50),@0_0_16 int,@0_1_0 datetime,@0_1_1 int,@0_1_2 int,@0_1_3 bit,@0_1_4 datetime,@0_1_5 datetime,@0_1_6 int,@0_1_7 varchar(max) ,@0_1_8 int,@0_1_9 bit,@0_1_10 bit,@0_1_11 int,@0_1_12 datetime,@0_1_13 varchar(50),@0_1_14 datetime,@0_1_15 varchar(50),@0_1_16 int',@0_0_0='2017-12-07 07:10:45.017',@0_0_1=432,@0_0_2=NULL,@0_0_3=1,@0_0_4=NULL,@0_0_5=NULL,@0_0_6=1,@0_0_7='Mail=r.worbis@cubido.at;Jahr=2005;',@0_0_8=NULL,@0_0_9=0,@0_0_10=NULL,@0_0_11=NULL,@0_0_12='2017-12-07 07:10:45.017',@0_0_13='SYSTEM',@0_0_14='2017-12-07 07:10:45.017',@0_0_15='SYSTEM',@0_0_16=0,@0_1_0='2017-12-07 07:10:45.127',@0_1_1=432,@0_1_2=NULL,@0_1_3=1,@0_1_4=NULL,@0_1_5=NULL,@0_1_6=1,@0_1_7='Mail=r.worbis@cubido.at;Jahr=2006;',@0_1_8=NULL,@0_1_9=0,@0_1_10=NULL,@0_1_11=NULL,@0_1_12='2017-12-07 07:10:45.127',@0_1_13='SYSTEM',@0_1_14='2017-12-07 07:10:45.127',@0_1_15='SYSTEM',@0_1_16=1
go
```

Best Regards,

Jonathan

**Comment by rworbis** [comment] 2017-12-08 10:10
Hello,

the provided SQL Statement works. You are right - there are trigger on that tables and if i deactivate them, the BulkSaveChanges works fine. (SaveChanges works also fine with the trigger)

If i add our trigger to your sample - everything works fine.

Attaced is a  File with the create statements for the trigger and the related table.

[SQLQuery1.txt](https://github.com/zzzprojects/EntityFramework-Extensions/files/1542243/SQLQuery1.txt)

**Comment by JonathanMagnan** [comment] 2017-12-08 13:57
Hello @rworbis ,

I'm just unsure since you closed the issue.

What exactly was causing the error? Is our library `BulkSaveChanges` compatible or not with your trigger?

Best Regards,

Jonathan

**Comment by rworbis** [comment] 2017-12-08 14:17
Hello,  i did close it without wanting to do so.
It seems BulkSaveChanges is not compatible

Regards,
Rainer

**Comment by JonathanMagnan** [comment] 2017-12-13 00:23
Hello @rworbis ,

Just to let you know we are still investigating this issue.

We currently use your table but are still unable to reproduce the error.

My developer suggested me to ask you to try on your side.

Since you already have the SQL executed, it's possible for you to try it in your environment directly using `SSMS` and check if the error is caused by the SQL generated by our library or if something we do is incompatible with your triggers?

We are currently running out of idea to try on our side ;)

Best Regards,

Jonathan

**Comment by rworbis** [comment] 2017-12-13 12:00
Hello,
i tried the sql you provided in our environment and fond the following error:

the first block looks like:
...
ON DestinationTable.[QueueId] = StagingTable.ZZZPredicate_75feb21112034aa49685fc91634cdbbe
WHEN MATCHED   THEN
    UPDATE
    SET     [QueueDatum] = StagingTable.[QueueDatum], [BerichtId] = StagingTable.[BerichtId], [BerichtGruppeId] = StagingTable.[BerichtGruppeId], [Aktiv] = StagingTable.[Aktiv], [StartDatum] = StagingTable.[StartDatum], [EndDatum] = StagingTable.[EndDatum], [Prioritaet] = StagingTable.[Prioritaet], [Beschreibung] = StagingTable.[Beschreibung], [ExternalQueueId] = StagingTable.[ExternalQueueId], [ErsetzeBenutzervariablen] = StagingTable.[ErsetzeBenutzervariablen], [QueueParameterBefuellen] = StagingTable.[QueueParameterBefuellen], [HistorieId] = StagingTable.[HistorieId], [BearbeitetAm] = StagingTable.[BearbeitetAm], [BearbeitetVon] = StagingTable.[BearbeitetVon], [ErstelltAm] = StagingTable.[ErstelltAm], [ErstelltVon] = StagingTable.[ErstelltVon]
;
MERGE INTO [dbo].[AR_QueueParameter] AS DestinationTable
USING
...
Note the ";" before the MERGE.

The second block (that throws the error looks like:
...
CREATE TABLE #ZZZProjects_81c0c488_139f_4aa3_ad74_01ff555f1f91z ( [$action] VARCHAR(100) NULL, ZZZ_Index INT NULL, [QueueId_zzzinserted] [sys].[int] NULL )
MERGE INTO [dbo].[AR_Queue] AS DestinationTable
USING
(
...
No ";" after MERGE - and that seems to be the error.

**Comment by JonathanMagnan** [comment] 2017-12-13 14:01
Hello @rworbis ,

Thank you for the help.

A `MERGE` must terminate with a semicolon, but other instruction such as CREATE TABLE doesn't have.

Perhaps there is an option that we are not aware to force it.

Anyway, we will try to reproduce it and add the semicolon to all our instructions.

A new version should be available later today.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment] 2017-12-14 20:09
Hello @rworbis ,

The v3.14.1 has been released:
http://entityframework-extensions.net/download

All statements should now have the semicolons ending.

Let me know if that fixes this issue or if you can find something else in your environment that's not compatible with the SQL statement generated.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment] 2018-01-09 20:53
Hello @rworbis ,

I will close this issue since it should be solved.

Feel free to reopen it if there is something else.

Best Regards,

Jonathan

**Closed by JonathanMagnan** 2018-01-09 20:53 UTC
