### ISSUE TITLE
BulkInsert - SQLite Error 1: 'cannot rollback - no transaction is active'.

### ISSUE THREAD

**Issue by vladrednic** [zzzprojects/EntityFramework-Extensions#208] opened 2019-04-24 15:15 UTC
### Description
I get the SQLite exception when trying to insert a batch of 100 with BulkInsert using IfNotExists option.
On one database it inserts successfully 60 batches and throws an error each time at batch 61.

### Exception
SQLite Error 1: 'cannot rollback - no transaction is active'.

I only get this error in production so I cannot reproduce it.

### Further technical details
- EF version: Microsoft.EntityDrameworkCore (2.1.4)
- EF Extensions version: Z.EntityFrameworkExtensions.EFCore (2.1.34)
- Database Provider: Microsoft.EntityFrameworkCore.Sqlite (2.1.4)

**Comment by JonathanMagnan** [comment] 2019-04-24 18:56
Hello @vladrednic ,

Thank you for reporting,

We will try to reproduce it on our side.

Best Regards,

Jonathan

**Comment by vladrednic** [comment] 2019-04-25 10:49
If you can reproduce it with and without the case presented in the description, it would tell us more about the issue.

Than you in advance.

**Comment by JonathanMagnan** [comment] 2019-04-25 13:41
Hello @vladrednic ,

We tried with your version and everything works fine on our side.

However, we investigate the error message: `SQLite Error 1: 'cannot rollback - no transaction is active'.`

SQLite creates a temporary file for transaction and some people report that might happen when the system volume is full or cause very similar to this one.

Could you make some check in your production environment? That will explain why it only happens here.

So far, I don't think that the issue is related to our library.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment] 2019-05-05 22:26
Hello @vladrednic ,

Did you succeed to fix your issue? Can we close this?

Best Regards,

Jonathan

**Comment by vladrednic** [comment] 2019-05-07 06:55
Hello @JonathanMagnan,

We narrowed it down to a database issue, but we are still investigating.
Thank you for the quick response. We can close it.

**Closed** 2019-05-07 09:35 UTC
