### ISSUE TITLE
EF6 + .DeleteFromQuery() works with Oracle but fails when the very same query runs on MsSqlServer and/or MySql

### ISSUE THREAD

**Issue by dsidirop** [zzzprojects/EntityFramework-Extensions#99] opened 2018-04-16 10:13 UTC
We are evaluating Z.EF.Extensions to see whether it fits the bill for our projects. We have stumbled upon an issue that appears to be plaguing Z.EF.Extensions in very much the same way that Z.EF.Plus is affected:

https://github.com/zzzprojects/EntityFramework-Plus/issues/229

The techniques we are using in order to support 3 dbs with the same .edmx are described in the link above. **The gist of it is that when the underlying EF driver employs CAST and/or Synonyms for the columns involved then operations like .DeleteWithQuery() tend to fail**. For instance in MySql the following EF query:

        _db
            .NB_STORED_FILTER_DEF
            .Where(x => filtersSetsIds.Contains(x.NSD_STORED_FILTER_ID))
            .AsNoTracking()
            .DeleteWithQuery(); 

Generates the following sql:

    DELETE A
    FROM `NB_STORED_FILTER_DEF` AS A
    INNER JOIN (
    	SELECT 
    		CAST(Extent1.NSD_ID AS SIGNED) AS C1   <--- problem right here with C1
        FROM
    		NB_STORED_FILTER_DEF AS Extent1
        WHERE
    		(CAST(Extent1.NSD_STORED_FILTER_ID AS SIGNED) IN (29047))
    		AND (CAST(Extent1.NSD_STORED_FILTER_ID AS SIGNED) IS NOT NULL)
    ) AS B ON A.`NSD_ID` = B.`NSD_ID`

**Comment by JonathanMagnan** [comment] 2018-04-16 12:27
Hello @dsidirop ,

Can we re-use the project you send us last year to reproduce it?
See: https://github.com/zzzprojects/EntityFramework-Plus/issues/229#issuecomment-327819983

If there is anything that has been changed, please make sure to update the project.

Upon your confirmation, I will assign it to one of my developers to understand more this issue.

Best Regards,

Jonathan

**Comment by dsidirop** [comment] 2018-04-16 12:30
Thank you for the prompt response. I will provide you with a new project written from scratch to help you reproduce the issue at hand under MySql/MsSqlServer.

Thanks again and stay tuned.

Regards,
Dominick Sidiropoulos

**Comment by JonathanMagnan** [comment] 2018-06-10 15:32
Hello @dsidirop ,

This issue will be closed since we haven't heard back from you.

Feel free to reopen it if you can provide the information we asked.

Best Regards,

Jonathan

**Closed by JonathanMagnan** 2018-06-10 15:32 UTC
