### ISSUE TITLE
.Include(a=>a.models) not working when the use .Futere() in ef core

### ISSUE THREAD

**Issue by alirezashakouri** [zzzprojects/EntityFramework-Extensions#110] opened 2018-05-15 08:51 UTC
Hi 
I,m Using Future() and .Include()  in Ef core Query
Like this:

//Main Object Name Is Visitor

```
var futureRecord = GetAll(r => r.Id == id).Include(q => q.VisitorInfo)
                .ThenInclude(t => t.VisitorInfoType).Include(visitor => visitor.Visit)
                .ThenInclude(visit => visit.Doctor).ThenInclude(doctor => doctor.User).Include(visitor => visitor.Visit)
                .ThenInclude(visitor => visitor.VisitType).Include(visitor => visitor.Visit)
                .ThenInclude(a => a.DateKeyNavigation).Include(a => a.BirthDateKeyNavigation).Future();

 var futureInsuranceList = _insuranceService.GetAll(a => true).Future();
```

but when getting record by 
` var record = futureRecord.FirstOrDefualt();`

the record related object has value but related ICollections Data Like 
'VisitorInfo and other ICollections Related Data.' dont have any data
but when remove the .Futer() All Work Fine

Like This:
 ```
var futureRecord = GetAll(r => r.Id == id).Include(q => q.VisitorInfo)
                .ThenInclude(t => t.VisitorInfoType).Include(visitor => visitor.Visit)
                .ThenInclude(visit => visit.Doctor).ThenInclude(doctor => doctor.User).
Include(visitor => visitor.Visit)
  .ThenInclude(visitor => visitor.VisitType).Include(visitor => visitor.Visit)
  .ThenInclude(a => a.DateKeyNavigation).Include(a => a.BirthDateKeyNavigation).ToList();

var futureInsuranceList = _insuranceService.GetAll(a => true).ToList();
```
.
.
.
`

**Comment by JonathanMagnan** [comment] 2018-05-16 21:26
Hello @alirezashakouri ,

You posted this request in the wrong library but that's fine. This request is beyond Entity Framework Plus.

Do you think you could provide us a project example/test with this issue?

It will make easier/faster for my developer to getting started for investigating it.

_We now always ask for a project since we found out that most issues are missing some essential information or are resolved by the requestor when creating it_

_(Even if the issue seem very easy to reproduce, by getting a test project, it allow us to give a faster support and better experience for the support of all our free libraries)_

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/) •  [LinqToSql Plus](http://linqtosql-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by alirezashakouri** [comment] 2018-05-18 07:09
I'm so busy!.but do it

**Comment by alirezashakouri** [comment] 2018-05-18 07:09
tanx

**Comment by JonathanMagnan** [comment] 2018-05-27 13:54
Hello @alirezashakouri ,

This issue will be closed since we haven't received any project form you.

We are sorry but we are so busy as well.

Best Regards,

Jonathan

**Closed by JonathanMagnan** 2018-05-27 13:54 UTC

**Comment by alirezashakouri** [comment] 2018-05-28 07:31
thanx.but if you want to fix this bug your developers can create a test
project with my code.Just fine

2018-05-27 18:24 GMT+04:30 Jonathan Magnan <notifications@github.com>:
