### ISSUE TITLE
InvalidOperationException on BulkMerge with IncludeGraph = true

### ISSUE THREAD

**Issue by Farami** [zzzprojects/EntityFramework-Extensions#62] opened 2017-11-13 08:21 UTC
Hi there,

EF Version 6.1.3
EF Extensions Version 3.13.8
Provider: SQL

we have run into another issue with BulkMerge this time.

The error message is "An entity object cannot be referenced by multiple instances of IEntityChangeTracker." in english.

The call:
`await this.dbContext.BulkMergeAsync(entities, options => options.IncludeGraph = true);`

The error:
`
[InvalidOperationException: Auf ein Entitätsobjekt kann nicht von mehreren Instanzen von IEntityChangeTracker verwiesen werden.]
   System.Data.Entity.Core.Objects.ObjectContext.VerifyContextForAddOrAttach(IEntityWrapper wrappedEntity) +5048129
   System.Data.Entity.Core.Objects.ObjectContext.AddSingleObject(EntitySet entitySet, IEntityWrapper wrappedEntity, String argumentName) +67
   System.Data.Entity.Core.Objects.ObjectContext.AddObject(String entitySetName, Object entity) +252
   System.Data.Entity.Internal.Linq.InternalSet``1.<AddRange>b__f(Object entity) +54
   System.Data.Entity.Internal.Linq.InternalSet``1.ActOnSet(Action``1 action, EntityState newState, IEnumerable entities, String methodName) +371
   System.Data.Entity.Internal.Linq.InternalSet``1.AddRange(IEnumerable entities) +79
   System.Data.Entity.DbSet``1.AddRange(IEnumerable``1 entities) +82
   DbContextExtensions.BulkMerge(DbContext this, IEnumerable``1 entities, Action``1 bulkOperationFactory) +329
   .() +82
   System.Threading.Tasks.Task.InnerInvoke() +73
   System.Threading.Tasks.Task.Execute() +47
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +99
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   .() +396
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +99
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   System.Runtime.CompilerServices.TaskAwaiter.GetResult() +26
   TrackPilotN.Data.Repositories.Generic.<InsertOrUpdateManyAsync>d__21.MoveNext() in C:\Users\paralikes\Source\TFS\PLT\Web\TrackPilotN.Data\Repositories\Generic\GenericRepository.cs:176
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +99
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   System.Runtime.CompilerServices.TaskAwaiter.GetResult() +26
   TrackPilotN.Business.Service.<EditOrInsertAddresses>d__60.MoveNext() in C:\Users\paralikes\Source\TFS\PLT\Web\TrackPilotN.Business\Service\AddressService.cs:950
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +99
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   System.Runtime.CompilerServices.TaskAwaiter``1.GetResult() +28
   TrackPilotN.Business.Service.<ImportAsync>d__58.MoveNext() in C:\Users\paralikes\Source\TFS\PLT\Web\TrackPilotN.Business\Service\AddressService.cs:916
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +99
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   System.Runtime.CompilerServices.TaskAwaiter``1.GetResult() +28
   TrackPilotN.Areas.Data.Controllers.<ImportConfirmed>d__14.MoveNext() in C:\Users\paralikes\Source\TFS\PLT\Web\TrackPilotN\Areas\Data\Controllers\AddressController.cs:291
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +99
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   System.Web.Mvc.Async.TaskAsyncActionDescriptor.EndExecute(IAsyncResult asyncResult) +97
   System.Web.Mvc.Async.<>c__DisplayClass37.<BeginInvokeAsynchronousActionMethod>b__36(IAsyncResult asyncResult) +17
   System.Web.Mvc.Async.WrappedAsyncResult``1.CallEndDelegate(IAsyncResult asyncResult) +10
   System.Web.Mvc.Async.WrappedAsyncResultBase``1.End() +48
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult) +32
   System.Web.Mvc.Async.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d() +50
   System.Web.Mvc.Async.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() +228
   System.Web.Mvc.Async.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() +228
   System.Web.Mvc.Async.<>c__DisplayClass33.<BeginInvokeActionMethodWithFilters>b__32(IAsyncResult asyncResult) +10
   System.Web.Mvc.Async.WrappedAsyncResult``1.CallEndDelegate(IAsyncResult asyncResult) +10
   System.Web.Mvc.Async.WrappedAsyncResultBase``1.End() +48
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult) +34
   System.Web.Mvc.Async.<>c__DisplayClass2b.<BeginInvokeAction>b__1c() +26
   System.Web.Mvc.Async.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult) +100
   System.Web.Mvc.Async.WrappedAsyncResult``1.CallEndDelegate(IAsyncResult asyncResult) +10
   System.Web.Mvc.Async.WrappedAsyncResultBase``1.End() +49
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult) +27
   System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState) +13
   System.Web.Mvc.Async.WrappedAsyncVoid``1.CallEndDelegate(IAsyncResult asyncResult) +29
   System.Web.Mvc.Async.WrappedAsyncResultBase``1.End() +49
   System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +36
   System.Web.Mvc.Controller.<BeginExecute>b__15(IAsyncResult asyncResult, Controller controller) +12
   System.Web.Mvc.Async.WrappedAsyncVoid``1.CallEndDelegate(IAsyncResult asyncResult) +22
   System.Web.Mvc.Async.WrappedAsyncResultBase``1.End() +49
   System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult) +26
   System.Web.Mvc.Controller.System.Web.Mvc.Async.IAsyncController.EndExecute(IAsyncResult asyncResult) +10
   System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState) +21
   System.Web.Mvc.Async.WrappedAsyncVoid``1.CallEndDelegate(IAsyncResult asyncResult) +29
   System.Web.Mvc.Async.WrappedAsyncResultBase``1.End() +49
   System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) +28
   System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.EndProcessRequest(IAsyncResult result) +9
   System.Web.CallHandlerExecutionStep.OnAsyncHandlerCompletion(IAsyncResult ar) +129
`

**Comment by JonathanMagnan** [comment] 2017-11-13 15:55
Hello @Farami ,

Thank you for reporting.

We will look at it today.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment] 2017-11-14 04:00
Hello @Farami ,

The issue is caused because some of your entities is a proxy type.

Unlike normal entity, proxy is `owned` by the original context which makes our `attach` method fail.

## Solution 1
The easiest solution is for this special case to disable proxy creation on your side with `ProxyCreationEnabled = false;`. So entity will not be longer be proxy

```csharp
var ctx1 = new CurrentContext();
var ctx2 = new CurrentContext();
ctx1.Configuration.ProxyCreationEnabled = false; // FAIL if true

var user = ctx1.Users.FirstOrDefault();
var group = new Group() { ColumnInt = 25 };
group.User = user;

ctx2.Groups.Add(group);
ctx2.SaveChanges();
```

## Solution 2 (_In Progress_)
We took some time to try to handle this scenario automatically

Unfortunately, so far, the only `trick` we have found is to `fake` the original context is disposed before adding and restoring the initial state after.

We don't like this idea since the proxy entity will be added to the second context which may bring some future issue.

---

Let me know if the solution 1 could work for you or if we need to investigate more for an automatic solution.

Best Regards,

Jonathan

**Comment by Farami** [comment] 2017-11-14 08:24
Hello @JonathanMagnan,

turning off proxy creation for **this** specific situation would be possible for us. However turning it off in general is not possible. We rely too much on lazy loading.

It would be great if you could further investigate an automatic solution.

**Comment by JonathanMagnan** [comment] 2017-11-14 14:21
Thank you @Farami ,

We will investigate more the second solution this week.

Best Regards,

Jonathan

**Comment by Farami** [comment] 2017-11-22 13:37
@JonathanMagnan Any new progress to share?

**Comment by JonathanMagnan** [comment] 2017-11-23 00:47
Hello @Farami ,

I will try to have the alternative solution working for next Monday if the fix passes all the test.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment] 2017-11-27 03:30
Hello @Farami ,

The v3.13.16 has been released.

`IncludeGraph` should now be compatible with `proxy` type. However, the setting `UnsafeMode` must be turned on.

The reason behind it is your `proxy` entities will temporary be moved to another context before being attached back to the original context.

```csharp
context.BulkInsert(list, options =>
	{
	  options.IncludeGraph = true;
	  options.UnsafeMode = true;
	});
```

Let me know if that's working on your side.

Best Regards,

Jonathan

**Comment by Farami** [comment] 2017-11-28 08:19
Hello @JonathanMagnan,

we seem to be running into an issue with that.
The error is:
`The EntityContainer name could not be determined. The provided EntitySet name must be qualified by the EntityContainer name, such as 'EntityContainerName.EntitySetName', or the DefaultContainerName property must be set for the ObjectContext.`


`
[ArgumentException: Der EntityContainer-Name konnte nicht bestimmt werden. Der angegebene EntitySet-Name muss durch den EntityContainer-Namen qualifiziert werden, wie z. B. 'EntityContainerName.EntitySetName', oder die Eigenschaft 'DefaultContainerName' muss für den ObjectContext festgelegt werden.
Parametername: entitySetName]
   System.Data.Entity.Core.Objects.ObjectContext.GetEntitySetName(String qualifiedName, String parameterName, ObjectContext context, String& entityset, String& container) +5045399
   System.Data.Entity.Core.Objects.ObjectContext.GetEntitySetFromName(String entitySetName) +40
   System.Data.Entity.Core.Objects.ObjectContext.VerifyRootForAdd(Boolean doAttach, String entitySetName, IEntityWrapper wrappedEntity, EntityEntry existingEntry, EntitySet& entitySet, Boolean& isNoOperation) +67
   System.Data.Entity.Core.Objects.ObjectContext.AttachTo(String entitySetName, Object entity) +167
   Z.EntityFramework.Extensions.EntityFrameworkManager.(DbContext , DbContext ) +529
   DbContextExtensions.BulkMerge(DbContext this, IEnumerable``1 entities, Action``1 bulkOperationFactory) +457
   .() +82
   System.Threading.Tasks.Task.InnerInvoke() +73
   System.Threading.Tasks.Task.Execute() +47
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +99
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   .() +396
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +99
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   System.Runtime.CompilerServices.TaskAwaiter.GetResult() +26
   TrackPilotN.Data.Repositories.Generic.<InsertOrUpdateManyAsync>d__21.MoveNext() in C:\Users\paralikes\Source\TFS\PLT\Web\TrackPilotN.Data\Repositories\Generic\GenericRepository.cs:176
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +99
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   System.Runtime.CompilerServices.TaskAwaiter.GetResult() +26
   TrackPilotN.Business.Service.<EditOrInsertAddresses>d__60.MoveNext() in C:\Users\paralikes\Source\TFS\PLT\Web\TrackPilotN.Business\Service\AddressService.cs:951
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +99
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   System.Runtime.CompilerServices.TaskAwaiter``1.GetResult() +28
   TrackPilotN.Business.Service.<ImportAsync>d__58.MoveNext() in C:\Users\paralikes\Source\TFS\PLT\Web\TrackPilotN.Business\Service\AddressService.cs:917
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +99
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   System.Runtime.CompilerServices.TaskAwaiter``1.GetResult() +28
   TrackPilotN.Areas.Data.Controllers.<ImportConfirmed>d__14.MoveNext() in C:\Users\paralikes\Source\TFS\PLT\Web\TrackPilotN\Areas\Data\Controllers\AddressController.cs:291
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +99
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   System.Web.Mvc.Async.TaskAsyncActionDescriptor.EndExecute(IAsyncResult asyncResult) +97
   System.Web.Mvc.Async.<>c__DisplayClass37.<BeginInvokeAsynchronousActionMethod>b__36(IAsyncResult asyncResult) +17
   System.Web.Mvc.Async.WrappedAsyncResult``1.CallEndDelegate(IAsyncResult asyncResult) +10
   System.Web.Mvc.Async.WrappedAsyncResultBase``1.End() +48
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult) +32
   System.Web.Mvc.Async.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d() +50
   System.Web.Mvc.Async.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() +228
   System.Web.Mvc.Async.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() +228
   System.Web.Mvc.Async.<>c__DisplayClass33.<BeginInvokeActionMethodWithFilters>b__32(IAsyncResult asyncResult) +10
   System.Web.Mvc.Async.WrappedAsyncResult``1.CallEndDelegate(IAsyncResult asyncResult) +10
   System.Web.Mvc.Async.WrappedAsyncResultBase``1.End() +48
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult) +34
   System.Web.Mvc.Async.<>c__DisplayClass2b.<BeginInvokeAction>b__1c() +26
   System.Web.Mvc.Async.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult) +100
   System.Web.Mvc.Async.WrappedAsyncResult``1.CallEndDelegate(IAsyncResult asyncResult) +10
   System.Web.Mvc.Async.WrappedAsyncResultBase``1.End() +48
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult) +27
   System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState) +13
   System.Web.Mvc.Async.WrappedAsyncVoid``1.CallEndDelegate(IAsyncResult asyncResult) +29
   System.Web.Mvc.Async.WrappedAsyncResultBase``1.End() +48
   System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +36
   System.Web.Mvc.Controller.<BeginExecute>b__15(IAsyncResult asyncResult, Controller controller) +12
   System.Web.Mvc.Async.WrappedAsyncVoid``1.CallEndDelegate(IAsyncResult asyncResult) +22
   System.Web.Mvc.Async.WrappedAsyncResultBase``1.End() +48
   System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult) +26
   System.Web.Mvc.Controller.System.Web.Mvc.Async.IAsyncController.EndExecute(IAsyncResult asyncResult) +10
   System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState) +21
   System.Web.Mvc.Async.WrappedAsyncVoid``1.CallEndDelegate(IAsyncResult asyncResult) +29
   System.Web.Mvc.Async.WrappedAsyncResultBase``1.End() +48
   System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) +28
   System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.EndProcessRequest(IAsyncResult result) +9
   System.Web.CallHandlerExecutionStep.OnAsyncHandlerCompletion(IAsyncResult ar) +129
`

**Comment by JonathanMagnan** [comment] 2017-11-28 14:02
Hello @Farami ,

Thank you for reporting. It seems that for some of your entities, the EntitySetName is empty or null.

We will try to reproduce this issue.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment] 2017-12-03 01:49
Hello @Farami ,

We tried some scenario on our side but we are not able to reproduce this issue.

Do you think you could provide us a project example that contains this bug?

Best Regards,

Jonathan

**Comment by Farami** [comment] 2017-12-05 08:01
I have sent you an E-Mail with the project attached.

**Comment by Farami** [comment] 2017-12-18 07:13
Hello @JonathanMagnan,

have you had time to check it out yet?

**Comment by JonathanMagnan** [comment] 2017-12-19 02:09
Hello @Farami ,

The v3.14.2 has been released today,

Could you try it? We successfully make it work with the project you provided.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment] 2018-01-09 20:32
Hello @Farami ,

I will close this issue. Feel free to reopen it if you still have the problem.

Best Regards,

Jonathan

**Closed by JonathanMagnan** 2018-01-09 20:32 UTC
