### ISSUE TITLE
Double request in log when using Query Future

### ISSUE THREAD

**Issue by Serproger** [zzzprojects/EntityFramework-Extensions#108] opened 2018-05-08 10:12 UTC
Hi! I'm using EF 6.2. When turning on logging (setting context.Database.Log to some delegate) I have such output for query that uses Future:
```
SELECT 
    [GroupBy1].[A1] AS [C1]
    FROM ( SELECT 
        COUNT(1) AS [A1]
        FROM [dbo].[FilterValues] AS [Extent1]
        WHERE @p__linq__0 IS NULL OR [Extent1].[FilterId] = @p__linq__1
    )  AS [GroupBy1]


-- p__linq__0: '1' (Type = Int32)

-- p__linq__1: '1' (Type = Int32)

-- Executing at 08.05.2018 13:57:19 +04:00

-- Completed in 0 ms with result: null



SELECT 
    [Project1].[Id] AS [Id], 
    [Project1].[FilterId] AS [FilterId], 
    [Project1].[Value] AS [Value], 
    [Project1].[SortKey] AS [SortKey]
    FROM ( SELECT 
        [Extent1].[Id] AS [Id], 
        [Extent1].[FilterId] AS [FilterId], 
        [Extent1].[Value] AS [Value], 
        [Extent1].[SortKey] AS [SortKey]
        FROM [dbo].[FilterValues] AS [Extent1]
        WHERE @p__linq__0 IS NULL OR [Extent1].[FilterId] = @p__linq__1
    )  AS [Project1]
    ORDER BY row_number() OVER (ORDER BY [Project1].[SortKey] ASC, [Project1].[Value] ASC, [Project1].[Id] ASC)
    OFFSET 0 ROWS 


-- p__linq__0: '1' (Type = Int32)

-- p__linq__1: '1' (Type = Int32)

-- Executing at 08.05.2018 13:57:19 +04:00

-- Completed in 0 ms with result: null



Opened connection at 08.05.2018 13:57:19 +04:00

-- EF+ Query Future: 1 of 2
SELECT 
    [GroupBy1].[A1] AS [C1]
    FROM ( SELECT 
        COUNT(1) AS [A1]
        FROM [dbo].[FilterValues] AS [Extent1]
        WHERE @Z_1_p__linq__0 IS NULL OR [Extent1].[FilterId] = @Z_1_p__linq__1
    )  AS [GroupBy1]
;

-- EF+ Query Future: 2 of 2
SELECT 
    [Project1].[Id] AS [Id], 
    [Project1].[FilterId] AS [FilterId], 
    [Project1].[Value] AS [Value], 
    [Project1].[SortKey] AS [SortKey]
    FROM ( SELECT 
        [Extent1].[Id] AS [Id], 
        [Extent1].[FilterId] AS [FilterId], 
        [Extent1].[Value] AS [Value], 
        [Extent1].[SortKey] AS [SortKey]
        FROM [dbo].[FilterValues] AS [Extent1]
        WHERE @Z_2_p__linq__0 IS NULL OR [Extent1].[FilterId] = @Z_2_p__linq__1
    )  AS [Project1]
    ORDER BY row_number() OVER (ORDER BY [Project1].[SortKey] ASC, [Project1].[Value] ASC, [Project1].[Id] ASC)
    OFFSET 0 ROWS 
;


-- Z_1_p__linq__0: '1' (Type = Int32)

-- Z_1_p__linq__1: '1' (Type = Int32)

-- Z_2_p__linq__0: '1' (Type = Int32)

-- Z_2_p__linq__1: '1' (Type = Int32)

-- Executing at 08.05.2018 13:57:19 +04:00

-- Completed in 0 ms with result: SqlDataReader



Closed connection at 08.05.2018 13:57:19 +04:00
```

First EF outputs two separate queries WITHOUT opening connection and after that single combined query WITH opening connection. How can I get rid of these separate queries in log?

**Comment by JonathanMagnan** [comment] 2018-05-08 10:53
Hello @Serproger ,

Do you think you could provide us a test project with this issue?

It will make easier/faster for my developer to getting started for investigating it.

_We now always ask for a project since we found out that most issues are missing some essential information or are resolved by the requestor when creating it_

_(Even if the issue seem very easy to reproduce, by getting a test project, it allow us to give a faster support and better experience for the support of all our free libraries)_

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/) •  [LinqToSql Plus](http://linqtosql-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by Serproger** [comment] 2018-05-08 10:56
I can but not immediately. It would be great if you checked this problem by yourself.

**Comment by JonathanMagnan** [comment] 2018-05-08 12:07
I’m sorry but we cannot.

It takes on averages 4h to fix and deploy a new version.

Without the minimum information to reproduce the issue, it cost me on average 150$ to pay a developer to make such request. That’s why we ask now for a project, to reduce this cost.

So, if you don’t have the time, feel free to contribute with a 150$ donation, and we will do our best to make all the works by ourselves: http://www.zzzprojects.com/contribute

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment] 2018-05-08 23:25
Thank a lot @Serproger ,

One of my developers will be assigned to this task.

Best Regards,

Jonathan

**Comment by Serproger** [comment] 2018-05-08 23:32
And one more question. Is it possible for you to implement interface IQuryable<T> in QueryFutureEnumerable class? I have some generic code that supposes that I use IQueryable and I can't run it for your QueryFutureEnumerable. I'm a bit sad :(

**Comment by JonathanMagnan** [comment] 2018-05-08 23:39
Hello @Serproger ,

This answer depends on multiple conditions.

If you can export the `InternalQuery` so that our library could retrieve it, perhaps it could be possible?

People normally set it in an internal property named `InnerQuery`.

See: https://github.com/zzzprojects/EntityFramework-Plus/blob/master/src/shared/Z.EF.Plus._Core.Shared/EF5_EF6/IQueryable%60/IQueryable%60.GetObjectQuery.cs#L49

So perhaps that could already work by using this property name on your side  ;)

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment] 2019-01-29 15:02
Hello @Serproger ,

We will close this request since we answered it.

If you need more help please re-open it on the right issue tracker: https://github.com/zzzprojects/EntityFramework-Plus

Best Regards,

Jonathan

**Closed by JonathanMagnan** 2019-01-29 15:02 UTC
