### ISSUE TITLE
System.Data.SqlClient.SqlException:'The multi-part identifier "a.object_id" could not be bound'

### ISSUE THREAD

**Issue by raouldc** [zzzprojects/EntityFramework-Extensions#3] opened 2016-05-03 00:25 UTC
BulkSaveChanges throws the following error:

> System.Data.SqlClient.SqlException:'The multi-part identifier "a.object_id" could not be bound'

This could be due to the fact that my database is Case Sensitive as a sql trace reveals the failure occurs on the following query: [query.txt](https://github.com/zzzprojects/EntityFramework-Extensions/files/246152/query.txt)

On line 77, the query is:

`OR a.object_id = OBJECT_ID(E.base_object_name)`

but it should be

`OR A.object_id = OBJECT_ID(E.base_object_name)`

**Comment by zzzprojects** [comment] 2016-05-03 00:49
Thank you Raoul,

We will check this tomorrow and release a fix for this issue. We will make some test to make sure everything is working with case sensitive database.

Best Regards,

Jonathan

**Comment by zzzprojects** [comment] 2016-05-04 12:56
Hello Raoul,

The version 3.9.27 is released fixing this issue.

We added tons of test with a case sensitive database.

Let us know if the issue is fixed for you.

**Comment by zzzprojects** [comment] 2016-05-13 15:49
Closing the issue, the request is completed & tested.

**Closed by zzzprojects** 2016-05-13 15:49 UTC
