### ISSUE TITLE
BatchDelete not working

### ISSUE THREAD

**Issue by nickyquinn** [zzzprojects/EntityFramework-Extensions#453] opened 2021-11-30 15:30 UTC
### Description
BatchDelete results in exception when used with npgsql in the context of an IQueryable with Delete() or DeleteAsync() being called.

This happens with any query utilising the Delete extension and appears to be because internally the SQL query being generated contains variables compatible with MSSQL and not postgres (vars start with an '@').

### Exception
If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message: Npgsql.PostgresException: 42601: syntax error at or near "@"
Stack trace:

[PostgresException (0x80004005): 42601: syntax error at or near "@"

POSITION: 11]
   Npgsql.Internal.<<ReadMessage>g__ReadMessageLong|213_0>d.MoveNext() +2864
   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +32
   Npgsql.<NextResult>d__47.MoveNext() +9860
   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +32
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +62
   Npgsql.NpgsqlDataReader.NextResult() +165
   Npgsql.<ExecuteReader>d__113.MoveNext() +2178
   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +32
   Npgsql.<ExecuteReader>d__113.MoveNext() +4299
   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +32
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +62
   Npgsql.<ExecuteScalar>d__104.MoveNext() +565
   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +32
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +62
   Npgsql.NpgsqlCommand.ExecuteScalar() +314
```

### Code
```
ctx.Reviews.Where(x => x.CreationDate < date).Delete();
```

### Further technical details
- EF version: 6.4.4
- EF Extensions version: 6.13.2
- Database Provider: EntityFramework6.Npgsql 6.4.3

**Comment by JonathanMagnan** [comment] 2021-11-30 16:12
Hello @nickyquinn ,

Thank you for reporting, my developer will look at it.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment] 2021-12-07 14:56
Hello @nickyquinn ,

My developer looked at it and everything is working.

The `@` is also used by PostgreSQL (I believe you can either use `@` and `:`) => https://stackoverflow.com/questions/32158014/postgresql-parameterized-insert-with-ado-net

Do you think you could create a runnable project with the issue? It doesn’t need to be your project, just a new solution with the minimum code to reproduce the issue.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment] 2021-12-12 20:34
Hello again, 

Since our last conversation, we haven't heard from you. 

Are you able to provide a runnable project with this issue? 

Let me know if you need further assistance. 

Best regards, 

Jon

**Comment by nickyquinn** [comment] 2021-12-15 12:51
Hi Jon,

Unfortunately I've not been able to reproduce this outside the project I'm working on; in a simple example starting with Postgresql and EF6 the function is fine, but in my more complicated project I still get the issue. The project is converted from using EF with MSSQL to EF with Postgresql, and this same delete call works fine with MSSQL, which is why I believe it to be specific to Postgresql.

Kind regards,

Nick

**Comment by JonathanMagnan** [comment] 2021-12-15 15:55
Thank you for the update @nickyquinn ,

We will close this issue, but if you can get us a project with the issue, we will be happy to re-open it.

Unfortunately, if you are not able to reproduce it, we will not be able either as we don't know what in your more complicated project makes this issue appears.

One thing you should check is if you have an interceptor or something that could intercept the query and add some parameters that could cause the issue.

Best Regards,

Jon

**Closed by JonathanMagnan** 2021-12-15 15:55 UTC

**Comment by nickyquinn** [comment] 2021-12-16 07:46
Hi Jon,

Thanks to your last comment, I was able to identify this issue; I did in fact have an interceptor (MiniProfiler) running that tracked connection open/closures. Once I disabled this, the error disappeared.

Many thanks for your support.

Kind regards,

Nick
