### ISSUE TITLE
StateManager created by BulkInsert has wrong the DeleteOrphansTiming value

### ISSUE THREAD

**Issue by thumer** [zzzprojects/EntityFramework-Extensions#512] opened 2022-11-02 17:49 UTC
## Description

We are crashing while updating an Entity Property, if we set a Navigation Property to NULL, if this Navigation is a Restricted Reference to an other entity. This would be correct, if `ChangeTracker.DeleteOrphansTiming = CascadeTiming.Immidiate` was set (default behavior).
But we have disabled this validation-behavior, by setting `ChangeTracker.DeleteOrphansTiming = CascadeTiming.OnSaveChanges` in Constructor of our DbContext. *(For info: ChangeTracker.DeleteOrphansTiming is a property of the underlying StateManager.DeleteOrphansTiming)*

## Exception
```
System.InvalidOperationException: The association between entities 'Wirtschaftsjahr' and 'Gegenbuchung' with the key value '{WirtschaftsjahrId: 8}' has been severed, but the relationship is either marked as required or is implicitly required because the foreign key is not nullable. If the dependent/child entity should be deleted when a required relationship is severed, configure the relationship to use cascade deletes.
```
StackTrace:
````
at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.HandleConceptualNulls(Boolean sensitiveLoggingEnabled, Boolean force, Boolean isCascadeDelete)
at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetProperty(IPropertyBase propertyBase, Object value, Boolean isMaterialization, Boolean setModified, Boolean isCascadeDelete, CurrentValueType valueType)
at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.ConditionallyNullForeignKeyProperties(InternalEntityEntry dependentEntry, InternalEntityEntry principalEntry, IForeignKey foreignKey)
at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.NavigationReferenceChanged(InternalEntityEntry entry, INavigationBase navigationBase, Object oldValue, Object newValue)
at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ChangeDetector.DetectNavigationChange(InternalEntityEntry entry, INavigationBase navigationBase)
at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ChangeDetector.PropertyChanged(InternalEntityEntry entry, IPropertyBase propertyBase, Boolean setModified)
at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.HandleINotifyPropertyChanged(Object sender, PropertyChangedEventArgs eventArgs)
[at RZL.Framework.Data.DomainObject.RaisePropertyChanged(String propertyName) in D:\2\s\Src\Framework\RZL.Framework.Data\DomainObject.cs:line 88](http://tfs.rzlsoftware.at:8080/tfs/RZL/RZL/_versionControl?path=%24%2FRZL%2FFeature%2FRZL_2.0%2FDotNet7/%2FSrc%2FFramework%2FRZL.Framework.Data%2FDomainObject.cs&version=&line=88&lineEnd=89&lineStartColumn=1&lineEndColumn=1&lineStyle=plainT&_a=contents)
at InvokeStub_Buchung.set_Wirtschaftsjahr(Object, Object, IntPtr*)
````

It only occured, if we have inserted this Entity via Z.EntityFramework.Extensions.EFCore -> **BulkInsert**. 

## Our Analysis

We found out, that BulkInsert creates some times a new StateManager and a new EntityEntry. **The Problem is, that this StateManager has the wrong DeleteOrphansTiming Setting of the original DbContext!**

*It has the Default Value DeleteOrphansTiming = CascadeTiming.Immidiate*

*The EntityEntry of this new StateManager is registred at the PropertyChanged-Event of the Navigation-Property. So it is validating - with the wrong behavior -> Exception was thrown*

This is a Code Snippet from ILSpy of Class `\ue002`
```
public static void \ue008<\ue001>(this BulkOperation<\ue001> @this, DbContext \ue028, IEntityType \ue029, IEnumerable<object> \ue02a, BulkOperationActionType \ue02b) where \ue001 : class
{
	@this.\ue090 = \ue028.\ue026();
	@this.\ue092 = \ue028.\ue024();
	@this.\ue093 = \ue028.\ue023();
	@this.\ue091 = \ue028.\ue027();
	@this.\ue094 = \ue028.\ue022();
	if (@this.\ue128 != null)
	{
		@this.\ue00a(\ue028, \ue029, \ue02a);
		return;
	}
	List<object> list = \ue02a.ToList();
	StateManager stateManager = null;
	Dictionary<string, IProperty> dictionary = new Dictionary<string, IProperty>();
	EntityTypeZInfo entityTypeZInfo = \ue029.ToZInfo();
	bool isKeyless = entityTypeZInfo.IsKeyless;
	if (@this.\ue09b || @this.\ue09a || @this.\ue099)
	{
		stateManager = (StateManager)\ue028.Database.GetService<IStateManager>();
	}
	else
	{
		StateManager stateManager2 = (StateManager)\ue028.Database.GetService<IStateManager>();
		stateManager = new StateManager(stateManager2.Dependencies);
	}
```
the **else-block** was running so a new StateManager was instantiated.

It would work if the **if-block** is running. Or it will also work, if this StateManager has the same behavior-Properties, like the original `stateManager2`.

### Further technical details
- EF version: 7.0.0-rc.2.22472.11
- EF Extensions version: 7.0.0-rc.2.22472.11-03
- Database Provider: Microsoft.EntityFrameworkCore.SqlServer

**Comment by JonathanMagnan** [comment] 2022-11-02 20:38
Hello @thumer ,

Do you think you could create a runnable project with the issue? It doesn’t need to be your project, just a new solution with the minimum code to reproduce the issue. You can send it in private here if you want: info@zzzprojects.com

That will surely help us to get started and make sure we have the same configuration as you since we never really played with the `DeleteOrphansTiming` from EF Core.

Best Regards,

Jon

**Comment by thumer** [comment] 2022-11-03 10:12
Here I have created a small project, where you can reproduce this behavior:

<details>
  <summary>MyDbContext.cs</summary>

  ```cs
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.Extensions.Options;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection.Emit;

namespace RZL;

public class MyDbContext : DbContext
{
    public MyDbContext(CascadeTiming? deleteOrphansTiming = null)
    {
        ChangeTracker.AutoDetectChangesEnabled = false;

        if (deleteOrphansTiming.HasValue)
            ChangeTracker.DeleteOrphansTiming = deleteOrphansTiming.Value;
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        base.OnConfiguring(optionsBuilder);
        optionsBuilder
            .UseSqlServer("Server=localhost;Database=EFCore_DeleteOrphansTimingIssue;Integrated Security=true;TrustServerCertificate=True");
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);

        modelBuilder.HasChangeTrackingStrategy(ChangeTrackingStrategy.ChangingAndChangedNotificationsWithOriginalValues);

        modelBuilder.Entity<Author>(b =>
        {
            b.ToTable("Authors");
        });
        modelBuilder.Entity<Book>(b =>
        {
            b.ToTable("Books");
            b.HasOne(x => x.Author)
             .WithMany()
             .HasForeignKey(x => x.AuthorId)
             .OnDelete(DeleteBehavior.Restrict);
            b.HasDiscriminator<byte>("Type").HasValue<Book>(0).HasValue<SpecialBook>(1);
        });
    }
    public DbSet<Author> Authors { get; set; }
    public DbSet<Book> Books { get; set; }
}

public class EntityBase : INotifyPropertyChanged, INotifyPropertyChanging
{
    public event PropertyChangedEventHandler? PropertyChanged;
    public event PropertyChangingEventHandler? PropertyChanging;
    protected void RaisePropertyChanging(string propertyName)
        => PropertyChanging?.Invoke(this, new PropertyChangingEventArgs(propertyName));

    protected void RaisePropertyChanged(string propertyName)
        => PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));

    public Delegate[] GetPropertyChangedHandlerForDiagnostic()
        => PropertyChanged.GetInvocationList();
    public InternalEntityEntry[] GetEntityEntriesForDiagnostic()
        => PropertyChanged.GetInvocationList().Select(d => d.Target as InternalEntityEntry).ToArray();
}

public sealed class Author : EntityBase
{
    private int _id;
    public int Id
    {
        get => _id;
        set
        {
            if (_id != value)
            {
                RaisePropertyChanging(nameof(Id));
                _id = value;
                RaisePropertyChanged(nameof(Id));
            }
        }
    }

    private string? _name;
    public string? Name
    {
        get => _name;
        set
        {
            if (_name != value)
            {
                RaisePropertyChanging(nameof(Name));
                _name = value;
                RaisePropertyChanged(nameof(Name));
            }
        }
    }
}

public sealed class SpecialBook : Book
{
    public string SpecialProperty { get; set; }
}

public class Book : EntityBase
{
    private int _id;
    public int Id
    {
        get => _id;
        set
        {
            if (_id != value)
            {
                RaisePropertyChanging(nameof(Id));
                _id = value;
                RaisePropertyChanged(nameof(Id));
            }
        }
    }

    private string? _title;
    public string? Title
    {
        get => _title;
        set
        {
            if (_title != value)
            {
                RaisePropertyChanging(nameof(Title));
                _title = value;
                RaisePropertyChanged(nameof(Title));
            }
        }
    }

    private int _authorId;
    public int AuthorId
    {
        get => _authorId;
        set
        {
            if (_authorId != value)
            {
                RaisePropertyChanging(nameof(AuthorId));
                _authorId = value;
                RaisePropertyChanged(nameof(AuthorId));
            }
        }
    }

    private Author _author;
    public Author Author
    {
        get => _author;
        set
        {
            if (_author != value)
            {
                RaisePropertyChanging(nameof(Author));
                _author = value;
                RaisePropertyChanged(nameof(Author));
            }
        }
    }
}
  ```
</details>

<details>
  <summary>Program.cs</summary>

  ```cs
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.Internal;

namespace RZL;

internal class Program
{
    private static async Task Main(string[] args)
    {
        await using (MyDbContext dbContext = new MyDbContext())
        {
            await dbContext.Database.EnsureDeletedAsync();
            await dbContext.Database.EnsureCreatedAsync();
        }

        await using (MyDbContext dbContext = new MyDbContext())
        {
            Author author = new () { Name = "Mr. X" };
            dbContext.Add(author);

            await dbContext.SaveChangesAsync();
        }

        //Case 1: Expected Exception at Navigation Property Setter
        await using (MyDbContext dbContext = new MyDbContext()) // Default: DeleteOrphansTiming: Immediate
        {
            Author author = await dbContext.Authors.FirstAsync();

            Book book = new Book()
            {
                Title = "Book1",
                Author = author
            };
            dbContext.Add(book);

            try
            {
                book.Author = null;
            }
            catch (InvalidOperationException)
            {
                //Expected Behavior with DeleteOrphansTiming: Immediate
            }
        }

        //Case 2: Expected Exception at SaveChanges
        await using (MyDbContext dbContext = new MyDbContext(CascadeTiming.OnSaveChanges))
        {
            Author author = await dbContext.Authors.FirstAsync();

            Book book = new Book()
            {
                Title = "Book1",
                Author = author
            };
            dbContext.Add(book);

            book.Author = null; // No Exception!

            try
            {
                await dbContext.SaveChangesAsync();
            }
            catch (InvalidOperationException)
            {
                //Expected Behavior with DeleteOrphansTiming: OnSaveChanges
            }
        }


        Z.EntityFramework.Extensions.EntityFrameworkManager.ContextFactory = c => new MyDbContext(CascadeTiming.OnSaveChanges);

        //Case 3: BulkInsertAsync causes Exception at Navigation Property Setter
        await using (MyDbContext dbContext = new MyDbContext(CascadeTiming.OnSaveChanges))
        {
            Author author = await dbContext.Authors.FirstAsync();

            Book book = new Book()
            {
                Title = "Book1",
                Author = author
            };
            dbContext.Add(book);

            var entityEntries = book.GetEntityEntriesForDiagnostic(); // here you see the InternalEntityEntry for the dbContext 
            await dbContext.BulkInsertAsync(new object[] { book }); // here there was created a StateManager with DeleteOrphansTiming: Immediate
            entityEntries = book.GetEntityEntriesForDiagnostic(); // here you see 2 InternalEntityEntry - a second one from the BulkInsert-StateManager

            //############UNEXPECTED EXCEPTION##############
            book.Author = null; // There should be no Exception -> but there is one, because the second InternalEntityEntry is registred at the PropertyChanged-Event

            try
            {
                await dbContext.SaveChangesAsync();
            }
            catch (InvalidOperationException)
            {
                //Expected Behavior with DeleteOrphansTiming: OnSaveChanges
            }
        }
    }
}
  ```
</details>

I have also sent it to you to [info@zzzprojects.com](mailto:info@zzzprojects.com)

**Comment by thumer** [comment] 2022-11-03 10:13
Hello Jon,
here I have created a small project, where you can reproduce this behavior.

Best Regards,

Thomas Humer

Am Mi., 2. Nov. 2022 um 21:38 Uhr schrieb Jonathan Magnan <
***@***.***>:

**Comment by JonathanMagnan** [comment] 2022-11-09 15:56
Hello @thumer ,

The latest version for RC2 now contains the fix for this issue. This version should work with the stable version of EF Core 7 as well, but in the wrong case scenario, we are releasing our stable version next Monday / Tuesday.

Best Regards,

Jon

**Closed** 2022-11-21 13:53 UTC
