### ISSUE TITLE
DbContextExtensions.UpdateFromQuery() not escaping SQL Server reserved words

### ISSUE THREAD

**Issue by sergey-netdev** [zzzprojects/EntityFramework-Extensions#25] opened 2017-01-13 17:35 UTC
```
                DB.UpdateFromQuery<ResellerPriceList>(
                    e => some predicate, 
                    e => new ResellerPriceList { Default = false });
```

This code crashes:

```
at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption)
at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
at \u0003.\u0001.\u0001(SqlCommand \u0002, BulkOperation \u0003, Int32 \u0004)\r\n   at \u0003.\u0001.\u0001(DbCommand \u0002, BulkOperation \u0003, Int32 \u0004)
at \u0003.\u0001.\b(\u0001 )
at \u0007.\u0002.\u0001(List`1 )
at \u001a.\u0002.\u0001(List`1 )
at \u001a.\u0006.\u0001(BulkOperation )
at Z.BulkOperations.BulkOperation`1.\u0001(IQueryable , IQueryable , Expression`1 )
at DbContextExtensions.UpdateFromQuery[TEntity](IQueryable`1 query, Expression`1 updateExpression, Action`1 bulkOperationFactory)
at DbContextExtensions.UpdateFromQuery[TEntity](IQueryable`1 query, Expression`1 updateExpression)
at DbContextExtensions.\u001e.\u0001()
at System.Threading.Tasks.Task.Execute()

```

SQL Profiler shows that it generates the following query:

```
exec sp_executesql N'MERGE INTO [dbo].[ResellerPriceLists] AS DestinationTable
USING
(
SELECT 
    1 AS [C1], 
    [Extent1].[Id] AS [Id]
    FROM [dbo].[ResellerPriceLists] AS [Extent1]
) AS StagingTable
ON StagingTable.Id = DestinationTable.Id
WHEN MATCHED THEN
    UPDATE
    SET     Default = @zzzupdate_1
;',N'@zzzupdate_1 bit',@zzzupdate_1=0

```

which is incorrect as `Default` should be escaped with `[]`.

**Comment by JonathanMagnan** [comment] 2017-01-13 19:41
Hello @sergey-netdev ,

Thank you for reporting this issue.

This issue will be fixed this weekend.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment] 2017-01-14 19:00
Hello @sergey-netdev ,

The v3.10.32 is now available.

Let us know if the issue is fixed for you.

Best Regards,

Jonathan

**Comment by sergey-netdev** [comment] 2017-01-15 00:24
Fixed! Thank you!

**Comment by JonathanMagnan** [comment] 2017-01-15 00:25
;)

**Closed by JonathanMagnan** 2017-01-15 00:25 UTC
