### ISSUE TITLE
BulkSaveChange PrimaryKeyException on Delete And Insert with the same key

### ISSUE THREAD

**Issue by JoseMancebo** [zzzprojects/EntityFramework-Extensions#185] opened 2019-01-31 08:39 UTC
I'm tring to include the BulkSaveChanges on my project using EF5 over .Net 4.0

I found a problem when i delete an item with Key=1, and then I insert an item with Key=1.
The original savechanges firstly execute the delete command and then the insert. But the BulkSaveChanges is executing first the Insert Command cuasing a logical PrimaryKey Exception...

**Comment by JonathanMagnan** [comment] 2019-02-01 05:20
Hello @JoseMancebo ,

Thank you for reporting. We will look at it.

I'm not sure if we will be able to fixe it as the `BulkSaveChanges` work differently for `EF6` and `EF5` is pretty old but we will definitely try it.

I will let you know if we are not able to reproduce it but your example seem very clear.

Best Regards,

Jonathan

**Comment by JoseMancebo** [comment] 2019-02-01 09:08
Hi @JonathanMagnan ,

I have prepared a sample project to reproduce it.
https://drive.google.com/file/d/1fIfN2RciRd5IeZf_HWbfySFNHtYjv2er/view?usp=sharing

I hope your help.

Best Regards,

Jose

**Comment by JonathanMagnan** [comment] 2019-02-11 21:07
Hello @JoseMancebo ,

We will close this issue.

As answered by email last week: "We tried to fix it during the weekend and again today, but unfortunately, it’s hard on our side to reproduce what we did in EF6 to have the same order as SaveChanges. Several methods from Entity Framework must be called to replicate it and it took us months to make it works correctly for EF6."

Unfortunately, since `EF5` is pretty old, we prefer to keep focusing the development on EF6 or EF Core.

Best Regards,

Jonathan

**Closed by JonathanMagnan** 2019-02-11 21:07 UTC
