### ISSUE TITLE
Any support for "Owned Entity Types" ?

### ISSUE THREAD

**Issue by AlirezaInGitHub** [zzzprojects/EntityFramework-Extensions#130] opened 2018-07-23 07:50 UTC
I just observed in my program that [owned entity types](https://docs.microsoft.com/en-us/ef/core/modeling/owned-entities) are not being stored in database.
Is this an issue or there is a workaround for it?

**Comment by JonathanMagnan** [comment] 2018-07-23 13:47
Hello @AlirezaInGitHub ,

Thank you for reporting, we will look at `owner entity types` today.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment] 2018-07-25 00:41
Hello @AlirezaInGitHub ,

The v2.1.23 has been released.

Let me know if you have run into an issue. The support for `owned` type has not been straightforward, so we might have missed something.

Best Regards,

Jonathan

**Comment by AlirezaInGitHub** [comment] 2018-07-26 04:34
Hey @JonathanMagnan.
It solved the initial problem however looks like a breaking change as all the `ulkMergeAsync<T>(this DbContext @this, IEnumerable<T> entities, Action<BulkOperation<T>> options) ` calls now fail with null reference exception. The stack trace is:
```
   at .`1.( )
   at .Read()
   at .()
   at .( , DbCommand )
   at .(List`1 )
   at Z.BulkOperations.BulkOperation.()
   at .[](DbContext this, IEnumerable`1 , Action`1 )
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DbContextExtensions.`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Connect.Infrastructure.DataAccess.Loan.LoanDataAccess.<BulkMergeAsync>d__4.MoveNext() in D:\Code\Sxxx\DataAccess\Loan\LoanDataAccess.cs:line 34
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  
```

**Comment by JonathanMagnan** [comment] 2018-07-26 15:41
Thank you for reporting @AlirezaInGitHub ,

We unlisted the latest version from NuGet.

On our side, all unit test and `BulkMerge` scenario are working.

We are currently trying to reproduce it.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment] 2018-07-26 20:01
Hello @AlirezaInGitHub ,

The v2.1.24 has been released.

We fixed an issue when an owned type was inside another owned type.

I asked my developer to continue to add some unit tests since I'm not sure it's the same issue as you.

If you still have a problem, could you try to make a standalone project and send us an example?

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment] 2018-08-01 23:56
Hello @AlirezaInGitHub ,

The v2.1.28 has been released.

We added a lot of additional tests and fixed a few additional case we missed.

Let me know if on your side you can still find some issue with the latest version.

Best Regards,

Jonathan

**Comment by AlirezaInGitHub** [comment] 2018-08-04 07:30
Hi @JonathanMagnan.
Yes, I can now confirm every thing is working perfectly.

Thanks.

**Comment by JonathanMagnan** [comment] 2018-08-06 18:02
Great ;)

I will close this issue. Feel free to reopen if you find something.

Best Regards,

Jonathan

**Closed by JonathanMagnan** 2018-08-06 18:02 UTC
