### ISSUE TITLE
Improved Error messages

### ISSUE THREAD

**Issue by IainCoSource** [zzzprojects/EntityFramework-Extensions#236] opened 2019-06-25 07:13 UTC
### Description
Exceptions returned when using include graph do not provide information to diagnose issue

### Exception
entityframework-extensions

```
Exception message: 
 {"Object reference not set to an instance of an object."} | System.NullReferenceException

Stack trace:

   at .[](DbContext this, IEnumerable`1 , Action`1 )
   at .(DbContext this, StateManager , IReadOnlyList`1 , Action`1 )
   at .(DbContext this, StateManager , IReadOnlyList`1 , Action`1 )
   at .(DbContext this, Action`1 )
   at .[](DbContext this, IEnumerable`1 , Action`1 )
   at Pims.Data.Repository.CategoryRepository.AddNew(List`1 categoryDataToAdd) 
```
"Z.EntityFramework.Extensions.EFCore"

### Fiddle or Project (Optional)
If you are able, 

```
    pimsContext.BulkInsert(categoryDataToAdd,options =>
            {
                options.IncludeGraph = true;
                options.IncludeGraphOperationBuilder = operation =>
                {
                    if (operation is BulkOperation<CategoryInformation>)
                    {
                        var bulk = (BulkOperation<CategoryInformation>) operation;
                        bulk.ColumnPrimaryKeyExpression = x => x.Id;
                    }
                    else if (operation is BulkOperation<Category_x_Product>)
                    {
                        var bulk = (BulkOperation<Category_x_Product>) operation;
                        bulk.ColumnPrimaryKeyExpression = x => new
                        {
                            x.CategoryData_Id,
                            x.ProductData_Id
                        };
                    }
                };
            });
```
If I remove the IncludeGraphOperationBuilder the error changes to 
```
System.ArgumentNullException: 'Value cannot be null.
Parameter name: entityType
```
Provide a Fiddle that reproduces the issue: https://dotnetfiddle.net/Uqe9sf

Or provide a project/solution that we can run to reproduce the issue.
- Make sure the project compile
- Make sure to provide only the code that is required to reproduce the issue, not the whole project
- You can send private code here: info@zzzprojects.com

Otherwise, make sure to include as much information as possible to help our team to reproduce the issue.

_Note: More information you provide, faster we can implement a solution._

### Further technical details
- EF version: Core2.2
- EF Extensions version: 2.5.4
- Database Provider: MSSql

**Comment by JonathanMagnan** [comment] 2019-06-25 10:53
Hello @IainCoSource ,

Thank you for reporting,

We will look at it if we are able to reproduce it.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment] 2019-06-28 14:05
Hello @IainCoSource ,

My developer looks at this issue yesterday and today, he is still unable to reproduce it.

We highly believe the error happen on this line `var entityType = @this.FindModelEntityType(list);` in our library. We are not able to find your Entity Type for an unknow reason.

Is it possible to share your model? Or provide a runnable solution which will be even better (You can send it in private here: info@zzzprojects.com)

Perharp it will help us to find out what we are missing

Here is an example of one of our test to get you started
```csharp
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Z.BulkOperations;

namespace Z.Lab.EFCore20
{
    public class Request_ManyToMany_IncludeGraph
    {
        public static void Execute()
        {
            // CLEAR
            using (var context = new CurrentContext())
            {
                context.Categories.RemoveRange(context.Categories);
                context.Products.RemoveRange(context.Products);
                context.Category_x_Products.RemoveRange(context.Category_x_Products);
                context.BulkSaveChanges();
            }

            // SEED
            using (var context = new CurrentContext())
            {
            }

            // TEST: new product, new category
            using (var context = new CurrentContext())
            {
                var product = new Product {Name = "Product_A"};
                var category = new Category {Name = "Category_A"};
                var category_x_product = new Category_x_Product();

                category.Category_x_Products = new List<Category_x_Product>();
                category.Category_x_Products.Add(category_x_product);

                category_x_product.Product = product;

                context.BulkInsert(new List<Category> {category}, options =>
                {
                    options.IncludeGraph = true;
                    options.IncludeGraphOperationBuilder = operation =>
                    {
                        if (operation is BulkOperation<Category>)
                        {
                            var bulk = (BulkOperation<Category>) operation;
                            bulk.ColumnPrimaryKeyExpression = x => x.ID;
                        }
                        else if (operation is BulkOperation<Category_x_Product>)
                        {
                            var bulk = (BulkOperation<Category_x_Product>) operation;
                            bulk.ColumnPrimaryKeyExpression = x => new
                            {
                                x.CategoryData_Id,
                                x.ProductData_Id
                            };
                        }
                    };
                });

                var list1 = context.Categories.Include(x => x.Category_x_Products).ThenInclude(x => x.Product).ToList();
            }
        }


        public class CurrentContext : DbContext
        {
            static CurrentContext()
            {
                var context = new CurrentContext();
                context.Database.EnsureCreated();
            }

            public DbSet<Category> Categories { get; set; }
            public DbSet<Product> Products { get; set; }
            public DbSet<Product> Category_x_Products { get; set; }

            protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
            {
                optionsBuilder.UseSqlServer(new SqlConnection(My.Config.ConnectionStrings.TestDatabase));

                base.OnConfiguring(optionsBuilder);
            }

            protected override void OnModelCreating(ModelBuilder modelBuilder)
            {
                modelBuilder.Entity<Category_x_Product>()
                    .HasKey(pt => new {pt.CategoryData_Id, pt.ProductData_Id});

                modelBuilder.Entity<Category_x_Product>()
                    .HasOne(pt => pt.Category)
                    .WithMany(p => p.Category_x_Products)
                    .HasForeignKey(pt => pt.CategoryData_Id);

                modelBuilder.Entity<Category_x_Product>()
                    .HasOne(pt => pt.Product)
                    .WithMany(t => t.Category_x_Products)
                    .HasForeignKey(pt => pt.ProductData_Id);
            }
        }

        public class Category
        {
            public int ID { get; set; }
            public string Name { get; set; }
            public List<Category_x_Product> Category_x_Products { get; set; }
        }

        public class Product
        {
            public int ID { get; set; }
            public string Name { get; set; }
            public List<Category_x_Product> Category_x_Products { get; set; }
        }

        public class Category_x_Product
        {
            public int CategoryData_Id { get; set; }
            public int ProductData_Id { get; set; }

            public Category Category { get; set; }
            public Product Product { get; set; }
        }
    }
}
```

**Comment by IainCoSource** [comment] 2019-07-01 06:34
> Hello @IainCoSource ,
> 
> My developer looks at this issue yesterday and today, he is still unable to reproduce it.
> 
> We highly believe the error happen on this line `var entityType = @this.FindModelEntityType(list);` in our library. We are not able to find your Entity Type for an unknow reason.
> 
> Is it possible to share your model? Or provide a runnable solution which will be even better (You can send it in private here: [info@zzzprojects.com](mailto:info@zzzprojects.com))
> 
> Perharp it will help us to find out what we are missing
> 
> Here is an example of one of our test to get you started
> 
> ```cs
> using System.Collections.Generic;
> using System.Data.SqlClient;
> using System.Linq;
> using Microsoft.EntityFrameworkCore;
> using Z.BulkOperations;
> 
> namespace Z.Lab.EFCore20
> {
>     public class Request_ManyToMany_IncludeGraph
>     {
>         public static void Execute()
>         {
>             // CLEAR
>             using (var context = new CurrentContext())
>             {
>                 context.Categories.RemoveRange(context.Categories);
>                 context.Products.RemoveRange(context.Products);
>                 context.Category_x_Products.RemoveRange(context.Category_x_Products);
>                 context.BulkSaveChanges();
>             }
> 
>             // SEED
>             using (var context = new CurrentContext())
>             {
>             }
> 
>             // TEST: new product, new category
>             using (var context = new CurrentContext())
>             {
>                 var product = new Product {Name = "Product_A"};
>                 var category = new Category {Name = "Category_A"};
>                 var category_x_product = new Category_x_Product();
> 
>                 category.Category_x_Products = new List<Category_x_Product>();
>                 category.Category_x_Products.Add(category_x_product);
> 
>                 category_x_product.Product = product;
> 
>                 context.BulkInsert(new List<Category> {category}, options =>
>                 {
>                     options.IncludeGraph = true;
>                     options.IncludeGraphOperationBuilder = operation =>
>                     {
>                         if (operation is BulkOperation<Category>)
>                         {
>                             var bulk = (BulkOperation<Category>) operation;
>                             bulk.ColumnPrimaryKeyExpression = x => x.ID;
>                         }
>                         else if (operation is BulkOperation<Category_x_Product>)
>                         {
>                             var bulk = (BulkOperation<Category_x_Product>) operation;
>                             bulk.ColumnPrimaryKeyExpression = x => new
>                             {
>                                 x.CategoryData_Id,
>                                 x.ProductData_Id
>                             };
>                         }
>                     };
>                 });
> 
>                 var list1 = context.Categories.Include(x => x.Category_x_Products).ThenInclude(x => x.Product).ToList();
>             }
>         }
> 
> 
>         public class CurrentContext : DbContext
>         {
>             static CurrentContext()
>             {
>                 var context = new CurrentContext();
>                 context.Database.EnsureCreated();
>             }
> 
>             public DbSet<Category> Categories { get; set; }
>             public DbSet<Product> Products { get; set; }
>             public DbSet<Product> Category_x_Products { get; set; }
> 
>             protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
>             {
>                 optionsBuilder.UseSqlServer(new SqlConnection(My.Config.ConnectionStrings.TestDatabase));
> 
>                 base.OnConfiguring(optionsBuilder);
>             }
> 
>             protected override void OnModelCreating(ModelBuilder modelBuilder)
>             {
>                 modelBuilder.Entity<Category_x_Product>()
>                     .HasKey(pt => new {pt.CategoryData_Id, pt.ProductData_Id});
> 
>                 modelBuilder.Entity<Category_x_Product>()
>                     .HasOne(pt => pt.Category)
>                     .WithMany(p => p.Category_x_Products)
>                     .HasForeignKey(pt => pt.CategoryData_Id);
> 
>                 modelBuilder.Entity<Category_x_Product>()
>                     .HasOne(pt => pt.Product)
>                     .WithMany(t => t.Category_x_Products)
>                     .HasForeignKey(pt => pt.ProductData_Id);
>             }
>         }
> 
>         public class Category
>         {
>             public int ID { get; set; }
>             public string Name { get; set; }
>             public List<Category_x_Product> Category_x_Products { get; set; }
>         }
> 
>         public class Product
>         {
>             public int ID { get; set; }
>             public string Name { get; set; }
>             public List<Category_x_Product> Category_x_Products { get; set; }
>         }
> 
>         public class Category_x_Product
>         {
>             public int CategoryData_Id { get; set; }
>             public int ProductData_Id { get; set; }
> 
>             public Category Category { get; set; }
>             public Product Product { get; set; }
>         }
>     }
> }
> ```

Will send you a model to info

**Comment by JonathanMagnan** [comment] 2019-07-14 14:24
Hello @IainCoSource ,

Did you get the time to create the runnable project?

**Comment by IainCoSource** [comment] 2019-07-18 03:54
Hi,

 

Unfortunately not yet still swamped

**Comment by JonathanMagnan** [comment] 2019-07-30 04:34
Hello @IainCoSource ,

We will close this issue, but as soon as you are able to provide the project, we will re-open it.

Best Regards,

Jonathan

**Closed by JonathanMagnan** 2019-07-30 04:34 UTC
