### ISSUE TITLE
NotSupportedException: The specified type member 'Id' is not supported in LINQ to Entities

### ISSUE THREAD

**Issue by MaxDotSouth** [zzzprojects/EntityFramework-Extensions#169] opened 2018-11-16 08:39 UTC
Hi, 

I think this a bug in UpdateFromQuery's query compilation. For some reason we use entities with interfaces (please don't judge as it does not explicate from this simplified code).
While the interface's property is not contained in the query expression, I get 

> member 'Id' is not supported

My code: 

```
public interface IBlah
    {
        [NotMapped]
        long Id { get; }
    }

public class MyEntity : IBlah
{
        public long ID { get; set; }
        public long Id { get => ID; }
        public string Comment { get; set; }
}
```

```
[TestMethod]
       public void TestMyEntity()
        {
            var ids = new long[] { -99 };
            //OK 
            var testresult = _db.MyEntity.Where(o => ids.Contains(o.ID)).ToList();

            //NotSupportedException
            _db.MyEntity.UpdateFromQuery(o => ids.Contains(o.ID)), o => new MyEntity() { Comment = "changed by unittest" });
        }
```

Why does UpdateFromQuery() need to touch Id when the query expression does not contain it?

**Comment by JonathanMagnan** [comment] 2018-11-16 13:42
Hello @MaxDotSouth ,

The way this query is currently built uses the `SELECT` statement generated by Entity Framework and make a join (on the primary key).

We will look at this scenario and fix it asap.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment] 2018-11-16 13:49
(Oops, forget the explanation above, we just checked more your case and it doesn't make sense ;) )

**Comment by JonathanMagnan** [comment] 2018-11-16 21:35
Hello @MaxDotSouth ,

My developer tried a few scenarios but was not able to reproduce it.

Here is the latest online scenario he tried: https://dotnetfiddle.net/Co31TU

Do you think you could provide us some hint about how to reproduce it? If you are able to reproduce that issue on .NET Fiddle, that would be the best.

Best Regards,

Jonathan

**Comment by MaxDotSouth** [comment] 2018-11-18 17:48
Hello Jonathan,

I tried to modify your code in a way to reproduce the error – with no success.
So I can just guess:


1.    Maybe it is related to the fact that my model is a DB generated edmx. But regarding the key attribute I can’t see a problem in the XML declaration. Also I do use _db.MyEntity.Find() successfully.

<EntityType Name="MyEntity">
          <Key>
            <PropertyRef Name="ID" />
          </Key>
          <Property Name="ID" Type="bigint" StoreGeneratedPattern="Identity" Nullable="false" />


2.    Your hint „… uses the SELECT statement generated by Entity Framework and make a join (on the primary key)“ made me stumble across EF’s conventions. Even if it’s a Code First – not a Db First - convention, maybe there is a connection to
https://docs.microsoft.com/en-us/ef/ef6/modeling/code-first/conventions/built-in#primary-key-convention


Either way, using Id and ID properties in one single class is naughty. So I refactored
Id
to a different name (let’s say MyId). Now my Unit Test is working ☺

Sorry for being of no help to reproduce the error in a neutral environment. Just hope that my thoughts help clarifying the source of this behaviour.

Best Regards,
max


Von: Jonathan Magnan <notifications@github.com>
Gesendet: Freitag, 16. November 2018 22:36
An: zzzprojects/EntityFramework-Extensions <EntityFramework-Extensions@noreply.github.com>
Cc: Massak Markus (BCC.IKT) <Markus.Massak@oebb.at>; Mention <mention@noreply.github.com>
Betreff: Re: [zzzprojects/EntityFramework-Extensions] NotSupportedException: The specified type member 'Id' is not supported in LINQ to Entities (#169)


Hello @MaxDotSouth<https://github.com/MaxDotSouth> ,

My developer tried a few scenarios but was not able to reproduce it.

Here is the latest online scenario he tried: https://dotnetfiddle.net/Co31TU

Do you think you could provide us some hint about how to reproduce it? If you are able to reproduce that issue on .NET Fiddle, that would be the best.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment] 2018-11-20 03:03
Hello @MaxDotSouth ,

Thank you for the additional information,

We will try again to reproduce it tomorrow.

**Comment by JonathanMagnan** [comment] 2018-11-20 20:08
Hello @MaxDotSouth ,

We didn't successfully reproduce it but we are currently re-writing this feature and it should no longer use the part that caused the error.

Since you fixed it in your side, could we close it?

Best Regards,

Jonathan

**Comment by MaxDotSouth** [comment] 2018-11-21 06:50
Hello Jonathan,
yes, please close it.

Thanks

Von: Jonathan Magnan <notifications@github.com>
Gesendet: Dienstag, 20. November 2018 21:09
An: zzzprojects/EntityFramework-Extensions <EntityFramework-Extensions@noreply.github.com>
Cc: Massak Markus (BCC.IKT) <Markus.Massak@oebb.at>; Mention <mention@noreply.github.com>
Betreff: Re: [zzzprojects/EntityFramework-Extensions] NotSupportedException: The specified type member 'Id' is not supported in LINQ to Entities (#169)


Hello @MaxDotSouth<https://github.com/MaxDotSouth> ,

We didn't successfully reproduce it but we are currently re-writing this feature and it should no longer use the part that caused the error.

Since you fixed it in your side, could we close it?

Best Regards,

Jonathan

**Closed** 2018-11-21 12:18 UTC
