### ISSUE TITLE
Invalid license key in linux

### ISSUE THREAD

**Issue by LeDucThang** [zzzprojects/EntityFramework-Extensions#301] opened 2019-11-05 03:34 UTC
### Description
i have a license key of entity framework core. I developed my project in windows and it runs ok. But when i bring my code and run it in ubuntu 18.04, it cannot validate my license key.
i tried run it in docker debian 9, and it's ok. I don't know why same code has difference behavious in difference OS environment

### Exception
If you are seeing an exception, include the full exceptions details (message and stack trace).
Unhandled Exception: System.Exception: ERROR_003: The provided license key is invalid or trial period is expired. Please buy a product license or go to https://zzzprojects.com/ and download the latest trial version. License Name: '2456;101-FPT';License Key: '....';MD5 Issue;
   at WG.Startup..ctor(IHostingEnvironment env) in /home/gitlab-runner/wegift/BE/WG/WG/Startup.cs:line 38
```
Exception message:
Stack trace:
```

### Further technical details
- EF version: 2.2.6
- EF Extensions version: 2.6.0
- Database Provider: SQLServer

**Comment by JonathanMagnan** [comment] 2019-11-05 13:59
Hello @LeDucThang ,

Could you try with the latest version?

Unfortunately, we have found an issue with string comparisons that work differently under Linux/ubuntu on the license validation which was throwing a similar issue.

The issue is already fixed in the latest version. I do not believe your version currently has this fix.

Best Regards,

Jonathan

**Comment by LeDucThang** [comment] 2019-11-08 07:40
Hello @JonathanMagnan 

My subscription expired on September, so i can't upgrade this library to the lastest version. Which other way can i use library in linux ?

Best  Regards,
Thang

**Comment by JonathanMagnan** [comment] 2019-11-08 13:47
Hello @LeDucThang ,

Please contact us directly with your company email.

We will provide you a license that's compatible with the latest version.

**Closed** 2019-12-30 14:24 UTC
