### ISSUE TITLE
Error while trying to BulkUpdate an Entity with a DateTime Column and an Array of string column

### ISSUE THREAD

**Issue by jeanarjean** [zzzprojects/EntityFramework-Extensions#427] opened 2021-07-21 14:13 UTC
### Description
Trying to BulkUpdate an Entity tracked by EF Core that has both a DateTime property and an Array of strings column causes the BulkUpdate operation to fail.

### Exception
```
Exception message: System.Exception
Oops! Unsupported types : ARRAY _text
   at .( , Exception , String[] )
   at .( , String[] )
   at .(Boolean , String[] )
   at .()
   at Z.BulkOperations.BulkOperation.()

System.Exception
Oops! Unsupported types : nodatime.instant
   at .( , String[] )

Stack trace:

System.Exception: An error occured while retrieving the InformationSchemaTable information. See the inner exception for details.

System.Exception
An error occured while retrieving the InformationSchemaTable information. See the inner exception for details.
   at Z.BulkOperations.BulkOperation.()
   at Z.BulkOperations.BulkOperation.Execute()
   at Z.BulkOperations.BulkOperation.BulkInsert()
   at .BulkInsert[T](DbContext this, IEntityType entityType, IEnumerable`1 list, Action`1 options, SavingSelector savingSelector, Boolean forceSpecificTypeMapping)
   at .BulkInsert[T](DbContext this, IEnumerable`1 entities, Action`1 options, Boolean isBulkSaveChanges)
   at DbContextExtensions.BulkInsert[T](DbContext this, IEnumerable`1 entities, Action`1 options)
   at DbContextExtensions.`1.()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at DbContextExtensions.BulkInsertAsync[T](DbContext this, IEnumerable`1 entities, Action`1 options, CancellationToken cancellationToken)
   at StoreProvider.SaveAsync(IEnumerable`1 requests) in /StoreProvider.cs:line 388
```

### Project Code

The class of the entity that to be updated

```c#
public class Entity
{
        public string Id { get; set; }

        public string[] Identifiers { get; set; }
        
        public DateTime DeletedAt { get; set; }
}
```
DbContextSnapshot of the class:
```
            modelBuilder.Entity("Directory.Infrastructure.Model.Entities.Entity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string[]>("Identifiers")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("identifiers");

                });
```
DbContext setup for the class:
```
            modelBuilder.Entity<Entity>(aggregate =>
            {
                aggregate.HasKey(x => new {x.Id});

                aggregate.Property(x => x.Id)
                    .HasMaxLength(64);
            });
```

**Comment by JonathanMagnan** [comment] 2021-07-21 14:30
Hello @jeanarjean ,

Could you let us know which provider you are using?

This is indeed the first time we see someone using a string array as a property.

Best Regards,

Jon

**Comment by jeanarjean** [comment] 2021-07-21 14:39
Hey @JonathanMagnan,

Thanks for the quick reply. We are using PostgresSQL through the package `Npgsql.EntityFrameworkCore.PostgreSQL`.

The BulkUpdate was working properly before, when the Entity only had a string array as a property, but since adding the DateTime property, the exception listed in the issue is being thrown. 

We also have a two other entities which have a DateTime property (but no string array) and are using the BulkInsert and they are working properly!

Jean-Raphael

**Comment by JonathanMagnan** [comment] 2021-07-21 14:42
Thank you for the additional information, I will assign this to my developer.

**Comment by JonathanMagnan** [comment] 2021-07-24 12:42
Hello @jeanarjean ,

My developer tried to reproduce it but unsuccesfully.

It is possible to have a runnable project with the minimum code required to reproduce the issue (You can send it in private here info@zzzprojects.com)? Or tell my developer what he is missing:

```csharp
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using static lab.EFCore30.PostgreSQL.Request_MergeIndexNotHere;

namespace Lab
{
    class Request_427
	{
		public static void Execute()
		{
			bool createAndDeleteBD = true;

			if (createAndDeleteBD)
			{
				// Create BD 
				using (var context = new EntityContext())
				{
					My.DeleteBD(context);
					context.Database.EnsureCreated();
				}
			}

			// CLEAN  
			using (var context = new EntityContext())
			{
				context.EntitySimples.RemoveRange(context.EntitySimples);

				context.SaveChanges();
			}


			// SEED  
			using (var context = new EntityContext())
			{
				context.EntitySimples.Add(new EntitySimple {Id = "1" , Identifiers =  new string[] {"test1", "test2" } });

				context.EntitySimples.Add(new EntitySimple { Id = "2", Identifiers = new string[] { "test1", "test2" } });

				context.EntitySimples.Add(new EntitySimple { Id = "3", Identifiers = new string[] { "test1", "test2" } });

				context.SaveChanges();
			}



			// TEST  
			using (var context = new EntityContext())
			{
				List<EntitySimple> list = new List<EntitySimple>();
				list.Add(new EntitySimple { Id = "10", Identifiers = new string[] { "test1", "test2" } });
				list.Add(new EntitySimple { Id = "100", Identifiers = new string[] { "test1", "test2" } });
				list.Add(new EntitySimple { Id = "1000", Identifiers = new string[] { "test1", "test2" } });

				context.BulkInsert(list);
			}
		}

		public class EntityContext : DbContext
		{
			public EntityContext()
			{
			}

			public DbSet<EntitySimple> EntitySimples { get; set; }

			protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
			{
				optionsBuilder.UseNpgsql(My.Connection);
			}

			protected override void OnModelCreating(ModelBuilder modelBuilder)
			{
				modelBuilder.Entity("Directory.Infrastructure.Model.Entities.Entity", b =>
				{
					b.Property<string>("Id")
						.HasMaxLength(64)
						.HasColumnType("character varying(64)")
						.HasColumnName("id");

					b.Property<DateTime>("DeletedAt")
						.HasColumnType("timestamp without time zone")
						.HasColumnName("deleted_at");

					b.Property<string[]>("Identifiers")
						.IsRequired()
						.HasColumnType("text[]")
						.HasColumnName("identifiers");

				});

				modelBuilder.Entity<EntitySimple>(aggregate =>
				{
					aggregate.HasKey(x => new { x.Id });

					aggregate.Property(x => x.Id)
						.HasMaxLength(64);
				});
			}
		}

		[Table("Directory.Infrastructure.Model.Entities.Entity")]
		public class EntitySimple
		{
			public string Id { get; set; } 
			public string[] Identifiers { get; set; }

			public DateTime DeletedAt { get; set; }
		}
	}
}
```

**Comment by JonathanMagnan** [comment] 2021-07-28 12:35
Hello @jeanarjean ,

Since our last conversation, we haven't heard from you!

Don't hesitate to provide a private runnable project with the minimum code required to reproduce the issue (info@zzzprojects.com)

Looking forward to hearing from you, 

Jon

**Comment by jeanarjean** [comment] 2021-07-28 12:43
Hey @JonathanMagnan ,

I've identified what is causing the problem on our side, I'll come back to you with a description today!

Best Regards,

Jean

**Comment by jeanarjean** [comment] 2021-07-28 21:48
Hey @JonathanMagnan,

I'm following up on my message from this morning, what was causing us the problem is the use of the UseNodaTime method when configuring a DbContext. The method modifies the NpgsqlConnection.GlobalTypeMapper which affects every DbContext in the application. I was able to reproduce the behaviour we get in our application by modifying the snippet you sent me:

```
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;

namespace Lab
{
    class Request_ArrayStringType_Text
    {
        public static void Execute()
        {
            bool createAndDeleteBD = true;

            if (createAndDeleteBD)
            {
                // Create BD 
                using (var context = new EntityContext())
                {
                    context.Database.EnsureDeleted();
                    context.Database.EnsureCreated();
                }
            }

            // CLEAN  
            using (var context = new EntityContext())
            {
                context.EntitySimples.RemoveRange(context.EntitySimples);

                context.SaveChanges();
            }


            // SEED  
            using (var context = new EntityContext())
            {
                context.EntitySimples.Add(new EntitySimple {Id = "1", Identifiers = new string[] {"test1", "test2"}});
                context.EntitySimples.Add(new EntitySimple {Id = "2", Identifiers = new string[] {"test1", "test2"}});
                context.EntitySimples.Add(new EntitySimple {Id = "3", Identifiers = new string[] {"test1", "test2"}});

                context.SaveChanges();
            }

            // TEST  
            using (var context = new EntityContext())
            {
                List<EntitySimple> list = new List<EntitySimple>();

                list.Add(new EntitySimple {Id = "10", Identifiers = new string[] {"test1", "test2"}});
                list.Add(new EntitySimple {Id = "100", Identifiers = new string[] {"test1", "test2"}});
                list.Add(new EntitySimple {Id = "1000", Identifiers = new string[] {"test1", "test2"}});

                context.BulkInsert(list);
            }

            using (var context = new EntityContext())
            {
                var t = context.EntitySimples.ToList();
            }
        }

        public class EntityContext : DbContext
        {
            public DbSet<EntitySimple> EntitySimples { get; set; }

            protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
            {
                optionsBuilder.UseNpgsql("User ID=postgres;Password=;Host=localhost;Port=5432;Database=date-test;",
                    sql => sql.UseNodaTime());
            }

            protected override void OnModelCreating(ModelBuilder modelBuilder)
            {
                modelBuilder.Entity<EntitySimple>(aggregate =>
                {
                    aggregate.HasKey(x => new {x.Id});

                    aggregate.Property(x => x.Id)
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id").HasMaxLength(64);

                    aggregate.Property(x => x.DeletedAt)
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    aggregate.Property(x => x.Identifiers)
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("identifiers");

                    aggregate.HasIndex(a => a.Identifiers);
                });
            }
        }

        public class EntitySimple
        {
            public string Id { get; set; }
            public string[] Identifiers { get; set; }

            public DateTime DeletedAt { get; set; }
        }
    }
}
```

**Comment by JonathanMagnan** [comment] 2021-07-29 14:09
Awesome,

Thank you, my developer will look at it.

**Comment by JonathanMagnan** [comment] 2021-08-04 01:52
Hello @jeanarjean ,

Unfortunately, you have currently hit one limitation of our library.

We either support  `NodaTime` or `ARRAY` for a specific table, but we didn't support both at the same time. Exactly as you initially said in your first post.

We will continue to investigate this issue but we cannot guarantee anything yet as it might require some breaking changes that we might not want to introduce right now.

**Closed** 2021-10-04 23:46 UTC
