### ISSUE TITLE
missing column on simple insertbulk call - postgre

### ISSUE THREAD

**Issue by faa-team** [zzzprojects/EntityFramework-Extensions#533] opened 2023-05-24 06:42 UTC
Hello, 
I am evaluating bulk libraries for our future project. I am not getting anywhere even at the simplest point. In BulkInsert it always throws me the error that the column is missing, no matter which table, it is always the first in the alphabet. We use Postgre SQL and Net.Core.

Missing Column : created_by
On entity : employee
On Table : "faa". "employee".

   at Z.BulkOperations.BulkOperation.()
   at Z.BulkOperations.BulkOperation.Execute()
   at .BulkInsert[T](DbContext this, IEntityType entityType, IEnumerable`1 list, Action`1 options, SavingSelector savingSelector, Boolean forceSpecificTypeMapping)
   at .BulkInsert[T](DbContext this, IEnumerable`1 entities, Action`1 options, Boolean isBulkSaveChanges)
   at DbContextExtensions.BulkInsert[T](DbContext this, IEnumerable`1 entities, Action`1 options)
   at DataServiceEf.MitarbeiterService.InsertList(List`1 items) in C:\Users\xxx\source\repos\xxx\\EFCore\DataServiceEf\MitarbeiterService.cs:line 84
   at Program.<<Main>$>d__0.MoveNext() in C:\Users\xxx\source\repos\xxx\EFCore\Client\Program.cs:line 50
   at Program.<Main>(String[] args)

or

   at Z.BulkOperations.BulkOperation.(String , Boolean , Boolean , Boolean )
   at Z.BulkOperations.BulkOperation.()

it is the simple call:

        public void InsertList(List<employee> items)
        {

            using (var context = new Entities(this.ConnectionString))
            {
                context.Employee.BulkInsert(items);
            }

        }
    }

**Comment by JonathanMagnan** [comment] 2023-05-24 13:40
Hello @faa-team ,

The error message is a little bit confusing the way it is written but in short, you currently have the `created_by` property of the `employee` mapped, but the column name `created_by` doesn't exists on the table "faa"."employee".

Could you double-check if it is right?

Otherwise, could you give us a simple example that we could try, such as your table creation and a code similar to this so we could reproduce the issue:

```csharp
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic; 
using System.Text;
using Npgsql;

namespace lab.EFCore60.PostgreSQL
{
    public class __Form_Template
    {
		public static void Execute()
		{
			bool createAndDeleteBD = true;

			if (createAndDeleteBD)
			{ 
				// Create BD 
				using (var context = new EntityContext())
				{
					My.DeleteBD(context);
					context.Database.EnsureCreated();
				}
			}

			// CLEAN  
			using (var context = new EntityContext())
			{
				context.EntitySimples.RemoveRange(context.EntitySimples);

				context.SaveChanges();
			}

			// SEED  
			using (var context = new EntityContext())
			{
				context.EntitySimples.Add(new EntitySimple { ColumnInt = 1 });

				context.EntitySimples.Add(new EntitySimple { ColumnInt = 2 });

				context.EntitySimples.Add(new EntitySimple { ColumnInt = 3 });

				context.SaveChanges();
			}

			// TEST  
			using (var context = new EntityContext())
			{
				List<EntitySimple> list = new List<EntitySimple>();
				list.Add(new EntitySimple { ColumnInt = 10 });
				list.Add(new EntitySimple { ColumnInt = 11 });
				list.Add(new EntitySimple { ColumnInt = 12 });

				context.BulkInsert(list);
			}
		}  
            
        public class EntityContext : DbContext
		{
			public EntityContext()  
			{ 
            }

            public DbSet<EntitySimple> EntitySimples { get; set; }

			protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
			{
			    optionsBuilder.UseNpgsql(My.Connection);
			}
        }

		public class EntitySimple
		{
			public int ID { get; set; }
			public int ColumnInt { get; set; }
			public String ColumnString { get; set; }
		} 
    }
}
```

**Comment by JonathanMagnan** [comment] 2023-05-29 13:24
Hello again, 

Since our last conversation, we haven't heard from you. 

Let me know if you need further assistance. 

Best regards, 

Jon

**Comment by faa-team** [comment] 2023-05-30 07:11
Hello Jon, 
sorry, we had holiday weekend in Germany. 

Sorry, I can't provide an example. We are working with Database-First and have the EF Core Power Tool create the Context.

        [Required]
        [Column("created_by")]
        [StringLength(255)]
        public string CreatedFrom { get; set; }

This is the named property. However, I don't think it's the property but the fact that it's the first one when reading in.

Thank you.

**Comment by faa-team** [comment] 2023-05-30 07:21
Hi Jon,

thinking again, it could be that this is a string property that can be null. But the database expects this value as non nullable. But on the column sits a trigger that automatically sets this value on insert?
That means to me that I don't set the property because the trigger does it.

**Comment by JonathanMagnan** [comment] 2023-06-13 13:44
Hello @faa-team ,

Sorry for the late reply. My developer is currently unable to reproduce it.

Do you think you could create a runnable project with the issue? It doesn’t need to be your project, just a new solution with the minimum code to reproduce the issue.  You can send it in private here if needed: info@zzzprojects.com

Here is a base case project that my developer created which is working if you want to start from it:

```csharp
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Text;
using Npgsql;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;

namespace Lab.PostgreSQL
{
	public class Request_Missing_Column
	{
		public static void Execute()
		{
			bool createAndDeleteBD = true;

			if (createAndDeleteBD)
			{
				// Create BD 
				using (var context = new EntityContext())
				{
					My.DeleteBD(context);
					context.Database.EnsureCreated();

					var connection = context.Database.GetDbConnection();
					connection.Open();
					using (var command = connection.CreateCommand())
                    {
						command.CommandText = @"CREATE OR REPLACE FUNCTION change_value() 
RETURNS TRIGGER AS '
BEGIN
    NEW.created_by = ''Test'';
    RETURN NEW;
END;
' LANGUAGE plpgsql;
;";

						command.ExecuteNonQuery();
					}

					using (var command = connection.CreateCommand())
					{
						command.CommandText = @"   
CREATE TRIGGER insert_entitysimples
    BEFORE INSERT ON entitysimples
        FOR EACH ROW
		EXECUTE FUNCTION change_value();
;";

						command.ExecuteNonQuery();
					}
				}
			} 

			// SEED  
			using (var context = new EntityContext())
			{
				context.EntitySimples.Add(new EntitySimple { ColumnInt = 1, ID = 1 });

				context.EntitySimples.Add(new EntitySimple { ColumnInt = 2, ID = 2 });

				context.EntitySimples.Add(new EntitySimple { ColumnInt = 3, ID = 3 });

				context.SaveChanges();
			}

			// SEED  
			using (var context = new EntityContext())
			{
				var check = context.EntitySimples.ToList(); 
			}

			// TEST  
			using (var context = new EntityContext())
			{
				List<EntitySimple> list = new List<EntitySimple>();
				list.Add(new EntitySimple { ColumnInt = 10, ID = 4 });
				list.Add(new EntitySimple { ColumnInt = 11, ID = 5 });
				list.Add(new EntitySimple { ColumnInt = 12, ID = 6 });

				context.BulkInsert(list);
			}

			// TEST  
			using (var context = new EntityContext())
			{
				List<EntitySimple> list = new List<EntitySimple>();

				for (int i = 7; i < 40; i++)
				{
					list.Add(new EntitySimple { ColumnInt = i, ID = i }); 
				}

				context.BulkInsert(list);
			}

			// SEED  
			using (var context = new EntityContext())
			{
				var check = context.EntitySimples.ToList();
			}
		}

		public class EntityContext : DbContext
		{
			public EntityContext()
			{
			}

			public DbSet<EntitySimple> EntitySimples { get; set; }

			protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
			{
				optionsBuilder.UseNpgsql(My.Connection);
			}
		}

		[Table("entitysimples")]
		public class EntitySimple
		{
			[DatabaseGenerated(DatabaseGeneratedOption.None)]
			public int ID { get; set; }
			public int ColumnInt { get; set; }
			[Required]
			[Column("created_by")]
			[StringLength(255)]
			public string CreatedFrom { get; set; }
		}
	}
}
```

**Comment by JonathanMagnan** [comment] 2023-06-26 14:04
Hello @faa-team 

Unfortunately, since we didn't hear from you I will close this issue. 

As previously mentioned, we need a runnable project to be able to assist you. 

We will reopen the issue if a project is received. 

Feel free to contact us for questions, issues or feedback.

Best Regards,

Jon

**Closed by JonathanMagnan** 2023-06-26 14:04 UTC
