### ISSUE TITLE
BulkInsert is getting failed with internal Connection fatal Error

### ISSUE THREAD

**Issue by prashant210392** [zzzprojects/EntityFramework-Extensions#456] opened 2021-12-14 13:11 UTC
Description
BulkInsert is getting failed with internal Connection fatal Error

```
Exception message:
 Internal Connection fatal Error

```
```
Stack trace:
  at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.TdsParser.Run(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj)
   at Microsoft.Data.SqlClient.SqlBulkCopy.RunParser(BulkCopySimpleResultSet bulkCopyHandler)
   at Microsoft.Data.SqlClient.SqlBulkCopy.CreateAndExecuteInitialQueryAsync(BulkCopySimpleResultSet& result)
   at Microsoft.Data.SqlClient.SqlBulkCopy.WriteToServerInternalRestAsync(CancellationToken cts, TaskCompletionSource`1 source)
   at Microsoft.Data.SqlClient.SqlBulkCopy.WriteToServerInternalAsync(CancellationToken ctoken)
   at Microsoft.Data.SqlClient.SqlBulkCopy.WriteRowSourceToServerAsync(Int32 columnCount, CancellationToken ctoken)
   at Microsoft.Data.SqlClient.SqlBulkCopy.WriteToServer(IDataReader reader)
   at .( , DbConnection , DbTransaction )
   at .( )
   at .( )
   at .Execute(List`1 actions)
   at .(List`1 )
   at Z.BulkOperations.BulkOperation.Execute()
   at Z.BulkOperations.BulkOperation.BulkInsert()
   at .BulkInsert[T](DbContext this, IEntityType entityType, IEnumerable`1 list, Action`1 options, SavingSelector savingSelector, Boolean forceSpecificTypeMapping)
   at .BulkInsert[T](DbContext this, IEnumerable`1 entities, Action`1 options, Boolean isBulkSaveChanges)
   at .(DbContext this, List`1 , Action`1 )
   at .(DbContext this, StateManager , IReadOnlyList`1 , Action`1 )
   at .(DbContext this, StateManager , IReadOnlyList`1 , Action`1 )
   at .(DbContext this, Action`1 , DbContext )
   at DbContextExtensions.(DbContext this, Action`1 , DbContext )
   at .BulkInsert[T](DbContext this, IEntityType entityType, IEnumerable`1 list, Action`1 options, SavingSelector savingSelector, Boolean forceSpecificTypeMapping)
   at .BulkInsert[T](DbContext this, IEnumerable`1 entities, Action`1 options, Boolean isBulkSaveChanges)
   at DbContextExtensions.BulkInsert[T](DbContext this, IEnumerable`1 entities, Action`1 options)
   at DbSetExtensions.BulkInsert[T](DbSet`1 this, IEnumerable`1 entities, Action`1 options)

```

_Note: 
This is getting failed when we are trying to bulkInsert more than 80 records, its working fine with less number of records.
current code
```
 public void BulkInsert(IEnumerable<T> entities)
        {
            _entities.BulkInsert(entities, operation => operation.IncludeGraph = true);
        }
```
where _entities is of type DbSet<T>.

we are confident issue is happening with bulkInsert because when we use AddRange of Micorsoft.EntityFrameworkCore.DbSet. the records are getting inserted and not getting any exception and changing it back to BulkInsert we are getting same error
```
 public void CreateRange(IEnumerable<T> entities)
        {
            _entities.AddRange(entities);
        }
```

### Further technical details
- EF version: Microsoft.EntityFrameworkCore (3.0.0)
- EF Extensions version: Z.EntityFramework.Extensions.EFCore (3.13.1)
- Database Provider: Azure Sql Server

**Comment by JonathanMagnan** [comment] 2021-12-14 14:28
Hello @prashant210392 ,

The `AddRange` doesn't save in the database. So we don't expect for sure any connection error here unless you call after `SaveChanges`.

I might be wrong, but I don't think this error is directly caused by our library.

For example, here is a very similar error as your: https://github.com/dotnet/SqlClient/issues/365#issuecomment-675599239 and the fix for this one: https://github.com/dotnet/SqlClient/issues/365#issuecomment-675689098

Another cause could be if you use some threads with the same context (so same connection).

I don't really have any idea why after 80 records.

Is it an issue you can easily repeat? If yes, do you think you could create a runnable project with the issue? It doesn’t need to be your project, just a new solution with the minimum code to reproduce the issue. You can send it in private here (info@zzzprojects.com)

At this moment, we are not sure how to reproduce it on our side as it looks more like an issue not related to our library but we can always be wrong.

Let me know if you find something more on your side or if you can provide something so we could investigate it.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment] 2021-12-15 17:23
We will wait for your project (let hope you find it how!), as we currently have no idea how to reproduce it on our side.

**Comment by JonathanMagnan** [comment] 2021-12-22 14:18
Hello again! 

Since our last conversation, we haven't heard from you. 

Were you able to create a runnable project? 

Let me know if you have any questions. 

Best regards, 

Jon

**Comment by JonathanMagnan** [comment] 2021-12-29 01:11
Hello @prashant210392, 

A simple reminder that we are here to assist you. 

Let me know if you can provide a runnable project?

Best regards, 

Jon

**Comment by prashant210392** [comment] 2021-12-29 05:18
Hi @JonathanMagnan 

We are able to replicate it easily in our lower as well as upper environment. as informed earlier changing bulkinsert with addrange followed by saveChange is working fine. The moment I revert it back to bulkinsert it’s getting failed.
People are on leave in holiday season. We will try to replicate it in standalone project post that.

**Comment by JonathanMagnan** [comment] 2021-12-29 14:07
Thank @prashant210392 ,

Sure, we will wait for your project

We will make a follow-up in around 3 weeks if nothing has been received yet.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment] 2022-01-19 16:15
Hello again! 

A simple follow-up to see if you had the chance to create a standalone project?

Let me know if you need further assistance. 

Best regards, 

Jon

**Comment by JonathanMagnan** [comment] 2022-02-02 13:52
Hello @prashant210392 ,

A simple reminder that we are here to assist you. 

Let me know if you had the time to create a standalone project. 

Best regards, 

Jon

**Closed** 2022-02-16 14:50 UTC
